// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enum.proto

#include "Enum.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace Protocol {
}  // namespace Protocol
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_Enum_2eproto[14];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_Enum_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_Enum_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_Enum_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\nEnum.proto\022\010Protocol*\263\002\n\rAnimationType"
  "\022\027\n\023ANIMATION_TYPE_NONE\020\000\022\027\n\023ANIMATION_T"
  "YPE_IDLE\020\001\022\027\n\023ANIMATION_TYPE_WALK\020\002\022\026\n\022A"
  "NIMATION_TYPE_RUN\020\003\022\031\n\025ANIMATION_TYPE_AT"
  "TACK\020\004\022\027\n\023ANIMATION_TYPE_ROLL\020\005\022\026\n\022ANIMA"
  "TION_TYPE_DIE\020\006\022\026\n\022ANIMATION_TYPE_HIT\020\007\022"
  "\036\n\032ANIMATION_TYPE_BOSS_APPEAR\020\010\022\035\n\031ANIMA"
  "TION_TYPE_BOSS_SPELL\020\t\022\034\n\030ANIMATION_TYPE"
  "_BOSS_CALL\020\n*\203\001\n\nObjectType\022\024\n\020OBJECT_TY"
  "PE_NONE\020\000\022\026\n\022OBJECT_TYPE_PLAYER\020\001\022\025\n\021OBJ"
  "ECT_TYPE_ENEMY\020\002\022\030\n\024OBJECT_TYPE_BUILDING"
  "\020\003\022\026\n\022OBJECT_TYPE_BULLET\020\004*h\n\nPlayerType"
  "\022\024\n\020PLAYER_TYPE_NONE\020\000\022\026\n\022PLAYER_TYPE_KN"
  "IGHT\020\001\022\024\n\020PLAYER_TYPE_MAGE\020\002\022\026\n\022PLAYER_T"
  "YPE_ARCHER\020\003*\221\001\n\tEnemyType\022\023\n\017ENEMY_TYPE"
  "_NONE\020\000\022\024\n\020ENEMY_TYPE_BASIC\020\001\022\025\n\021ENEMY_T"
  "YPE_ARCHER\020\002\022\026\n\022ENEMY_TYPE_WARRIOR\020\003\022\023\n\017"
  "ENEMY_TYPE_BOSS\020\004\022\025\n\021ENEMY_TYPE_MUTANT\020\005"
  "*\316\003\n\014BuildingType\022\026\n\022BUILDING_TYPE_NONE\020"
  "\000\022\027\n\023BUILDING_TYPE_GRASS\020\001\022\030\n\024BUILDING_T"
  "YPE_GROUND\020\002\022\033\n\027BUILDING_TYPE_BUILDING1\020"
  "\003\022\033\n\027BUILDING_TYPE_BUILDING2\020\004\022\033\n\027BUILDI"
  "NG_TYPE_BUILDING3\020\005\022\033\n\027BUILDING_TYPE_BUI"
  "LDING4\020\006\022\033\n\027BUILDING_TYPE_BUILDING5\020\007\022\033\n"
  "\027BUILDING_TYPE_BUILDING6\020\010\022\033\n\027BUILDING_T"
  "YPE_BUILDING7\020\t\022\033\n\027BUILDING_TYPE_BUILDIN"
  "G8\020\n\022\033\n\027BUILDING_TYPE_BUILDING9\020\013\022\036\n\032BUI"
  "LDING_TYPE_VILLAGE_WALL\020\014\022\033\n\027BUILDING_TY"
  "PE_DIRT_ROAD\020\r\022\027\n\023BUILDING_TYPE_TOWER\020\016\022"
  "\030\n\024BUILDING_TYPE_CASTLE\020\017*\201\001\n\013PlayerStat"
  "e\022\025\n\021PLAYER_STATE_NONE\020\000\022\025\n\021PLAYER_STATE"
  "_IDLE\020\001\022\025\n\021PLAYER_STATE_MOVE\020\002\022\027\n\023PLAYER"
  "_STATE_ATTACK\020\003\022\024\n\020PLAYER_STATE_DIE\020\004*\232\001"
  "\n\nEnemyState\022\024\n\020ENEMY_STATE_NONE\020\000\022\024\n\020EN"
  "EMY_STATE_IDLE\020\001\022\024\n\020ENEMY_STATE_MOVE\020\002\022\026"
  "\n\022ENEMY_STATE_ATTACK\020\003\022\023\n\017ENEMY_STATE_DI"
  "E\020\004\022\035\n\031ENEMY_STATE_SPAWN_PENDING\020\005*b\n\tGa"
  "meState\022\023\n\017GAME_STATE_NONE\020\000\022\024\n\020GAME_STA"
  "TE_LOBBY\020\001\022\026\n\022GAME_STATE_PLAYING\020\002\022\022\n\016GA"
  "ME_STATE_END\020\003*z\n\nWeaponType\022\024\n\020WEAPON_T"
  "YPE_NONE\020\000\022\025\n\021WEAPON_TYPE_SWORD\020\001\022\023\n\017WEA"
  "PON_TYPE_BOW\020\002\022\023\n\017WEAPON_TYPE_AXE\020\003\022\025\n\021W"
  "EAPON_TYPE_CANON\020\004*r\n\nBulletType\022\024\n\020BULL"
  "ET_TYPE_NONE\020\000\022\025\n\021BULLET_TYPE_ARROW\020\001\022\032\n"
  "\026BULLET_TYPE_CANNONBALL\020\002\022\033\n\027BULLET_TYPE"
  "_BOSS_POISON\020\003*\263\001\n\025ForcedTransformReason"
  "\022 \n\034FORCED_TRANSFORM_REASON_NONE\020\000\022(\n$FO"
  "RCED_TRANSFORM_REASON_TOWER_PORTAL\020\001\022)\n%"
  "FORCED_TRANSFORM_REASON_CASTLE_PORTAL\020\002\022"
  "#\n\037FORCED_TRANSFORM_REASON_RESPAWN\020\003*\230\001\n"
  "\020DebugCommandType\022\026\n\022DEBUG_COMMAND_NONE\020"
  "\000\022$\n DEBUG_COMMAND_KILL_MEGA5_ENEMIES\020\001\022"
  "\'\n#DEBUG_COMMAND_TELEPORT_TO_MEGA_GRID\020\002"
  "\022\035\n\031DEBUG_COMMAND_DAMAGE_BOSS\020\003*\256\001\n\010Item"
  "Type\022\022\n\016ITEM_TYPE_NONE\020\000\022\031\n\025ITEM_TYPE_HE"
  "AL_POTION\020\001\022!\n\035ITEM_TYPE_ATTACK_POWER_PO"
  "TION\020\002\022\034\n\030ITEM_TYPE_DEFENSE_POTION\020\003\022\037\n\033"
  "ITEM_TYPE_MOVE_SPEED_POTION\020\004\022\021\n\rITEM_TY"
  "PE_KEY\020\005*\331\001\n\rBossRoomState\022#\n\037BOSS_ROOM_"
  "STATE_PRE_BOSS_COMBAT\020\000\022\"\n\036BOSS_ROOM_STA"
  "TE_SUMMON_FADE_IN\020\001\022\"\n\036BOSS_ROOM_STATE_B"
  "OSS_APPEARING\020\002\022\037\n\033BOSS_ROOM_STATE_BOSS_"
  "ACTIVE\020\003\022\035\n\031BOSS_ROOM_STATE_BOSS_DEAD\020\004\022"
  "\033\n\027BOSS_ROOM_STATE_CLEARED\020\005b\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_Enum_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Enum_2eproto = {
  false, false, 2556, descriptor_table_protodef_Enum_2eproto, "Enum.proto", 
  &descriptor_table_Enum_2eproto_once, nullptr, 0, 0,
  schemas, file_default_instances, TableStruct_Enum_2eproto::offsets,
  nullptr, file_level_enum_descriptors_Enum_2eproto, file_level_service_descriptors_Enum_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_Enum_2eproto_getter() {
  return &descriptor_table_Enum_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_Enum_2eproto(&descriptor_table_Enum_2eproto);
namespace Protocol {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AnimationType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[0];
}
bool AnimationType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ObjectType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[1];
}
bool ObjectType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PlayerType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[2];
}
bool PlayerType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EnemyType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[3];
}
bool EnemyType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* BuildingType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[4];
}
bool BuildingType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PlayerState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[5];
}
bool PlayerState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EnemyState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[6];
}
bool EnemyState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* GameState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[7];
}
bool GameState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* WeaponType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[8];
}
bool WeaponType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* BulletType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[9];
}
bool BulletType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ForcedTransformReason_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[10];
}
bool ForcedTransformReason_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DebugCommandType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[11];
}
bool DebugCommandType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ItemType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[12];
}
bool ItemType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* BossRoomState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[13];
}
bool BossRoomState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
