// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enum.proto

#include "Enum.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace Protocol {
}  // namespace Protocol
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_Enum_2eproto[10];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_Enum_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_Enum_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_Enum_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\nEnum.proto\022\010Protocol*\276\001\n\rAnimationType"
  "\022\027\n\023ANIMATION_TYPE_NONE\020\000\022\027\n\023ANIMATION_T"
  "YPE_IDLE\020\001\022\027\n\023ANIMATION_TYPE_WALK\020\002\022\026\n\022A"
  "NIMATION_TYPE_RUN\020\003\022\031\n\025ANIMATION_TYPE_AT"
  "TACK\020\004\022\027\n\023ANIMATION_TYPE_ROLL\020\005\022\026\n\022ANIMA"
  "TION_TYPE_DIE\020\006*\203\001\n\nObjectType\022\024\n\020OBJECT"
  "_TYPE_NONE\020\000\022\026\n\022OBJECT_TYPE_PLAYER\020\001\022\025\n\021"
  "OBJECT_TYPE_ENEMY\020\002\022\030\n\024OBJECT_TYPE_BUILD"
  "ING\020\003\022\026\n\022OBJECT_TYPE_BULLET\020\004*h\n\nPlayerT"
  "ype\022\024\n\020PLAYER_TYPE_NONE\020\000\022\026\n\022PLAYER_TYPE"
  "_KNIGHT\020\001\022\024\n\020PLAYER_TYPE_MAGE\020\002\022\026\n\022PLAYE"
  "R_TYPE_ARCHER\020\003*z\n\tEnemyType\022\023\n\017ENEMY_TY"
  "PE_NONE\020\000\022\024\n\020ENEMY_TYPE_BASIC\020\001\022\025\n\021ENEMY"
  "_TYPE_ARCHER\020\002\022\026\n\022ENEMY_TYPE_WARRIOR\020\003\022\023"
  "\n\017ENEMY_TYPE_BOSS\020\004*\207\001\n\014BuildingType\022\026\n\022"
  "BUILDING_TYPE_NONE\020\000\022\026\n\022BUILDING_TYPE_WA"
  "LL\020\001\022\027\n\023BUILDING_TYPE_TOWER\020\002\022\026\n\022BUILDIN"
  "G_TYPE_BASE\020\003\022\026\n\022BUILDING_TYPE_TREE\020\004*\201\001"
  "\n\013PlayerState\022\025\n\021PLAYER_STATE_NONE\020\000\022\025\n\021"
  "PLAYER_STATE_IDLE\020\001\022\025\n\021PLAYER_STATE_MOVE"
  "\020\002\022\027\n\023PLAYER_STATE_ATTACK\020\003\022\024\n\020PLAYER_ST"
  "ATE_DIE\020\004*{\n\nEnemyState\022\024\n\020ENEMY_STATE_N"
  "ONE\020\000\022\024\n\020ENEMY_STATE_IDLE\020\001\022\024\n\020ENEMY_STA"
  "TE_MOVE\020\002\022\026\n\022ENEMY_STATE_ATTACK\020\003\022\023\n\017ENE"
  "MY_STATE_DIE\020\004*b\n\tGameState\022\023\n\017GAME_STAT"
  "E_NONE\020\000\022\024\n\020GAME_STATE_LOBBY\020\001\022\026\n\022GAME_S"
  "TATE_PLAYING\020\002\022\022\n\016GAME_STATE_END\020\003*z\n\nWe"
  "aponType\022\024\n\020WEAPON_TYPE_NONE\020\000\022\025\n\021WEAPON"
  "_TYPE_SWORD\020\001\022\023\n\017WEAPON_TYPE_BOW\020\002\022\023\n\017WE"
  "APON_TYPE_AXE\020\003\022\025\n\021WEAPON_TYPE_CANON\020\004*U"
  "\n\nBulletType\022\024\n\020BULLET_TYPE_NONE\020\000\022\025\n\021BU"
  "LLET_TYPE_ARROW\020\001\022\032\n\026BULLET_TYPE_CANNONB"
  "ALL\020\002b\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_Enum_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Enum_2eproto = {
  false, false, 1293, descriptor_table_protodef_Enum_2eproto, "Enum.proto", 
  &descriptor_table_Enum_2eproto_once, nullptr, 0, 0,
  schemas, file_default_instances, TableStruct_Enum_2eproto::offsets,
  nullptr, file_level_enum_descriptors_Enum_2eproto, file_level_service_descriptors_Enum_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_Enum_2eproto_getter() {
  return &descriptor_table_Enum_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_Enum_2eproto(&descriptor_table_Enum_2eproto);
namespace Protocol {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AnimationType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[0];
}
bool AnimationType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ObjectType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[1];
}
bool ObjectType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PlayerType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[2];
}
bool PlayerType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EnemyType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[3];
}
bool EnemyType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* BuildingType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[4];
}
bool BuildingType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PlayerState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[5];
}
bool PlayerState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EnemyState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[6];
}
bool EnemyState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* GameState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[7];
}
bool GameState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* WeaponType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[8];
}
bool WeaponType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* BulletType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[9];
}
bool BulletType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
