// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Protocol_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Protocol_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Enum.pb.h"
#include "Struct.pb.h"
#include "InitStruct.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Protocol_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Protocol_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[11]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Protocol_2eproto;
namespace Protocol {
class C_CLIENT_READY;
struct C_CLIENT_READYDefaultTypeInternal;
extern C_CLIENT_READYDefaultTypeInternal _C_CLIENT_READY_default_instance_;
class C_DEBUG_COMMAND;
struct C_DEBUG_COMMANDDefaultTypeInternal;
extern C_DEBUG_COMMANDDefaultTypeInternal _C_DEBUG_COMMAND_default_instance_;
class C_ENTER_GAME;
struct C_ENTER_GAMEDefaultTypeInternal;
extern C_ENTER_GAMEDefaultTypeInternal _C_ENTER_GAME_default_instance_;
class C_GAME_START;
struct C_GAME_STARTDefaultTypeInternal;
extern C_GAME_STARTDefaultTypeInternal _C_GAME_START_default_instance_;
class C_INPUT;
struct C_INPUTDefaultTypeInternal;
extern C_INPUTDefaultTypeInternal _C_INPUT_default_instance_;
class C_LOGIN;
struct C_LOGINDefaultTypeInternal;
extern C_LOGINDefaultTypeInternal _C_LOGIN_default_instance_;
class S_ENTER_GAME;
struct S_ENTER_GAMEDefaultTypeInternal;
extern S_ENTER_GAMEDefaultTypeInternal _S_ENTER_GAME_default_instance_;
class S_FORCED_TRANSFORM;
struct S_FORCED_TRANSFORMDefaultTypeInternal;
extern S_FORCED_TRANSFORMDefaultTypeInternal _S_FORCED_TRANSFORM_default_instance_;
class S_FRAME_STATE;
struct S_FRAME_STATEDefaultTypeInternal;
extern S_FRAME_STATEDefaultTypeInternal _S_FRAME_STATE_default_instance_;
class S_GAME_START;
struct S_GAME_STARTDefaultTypeInternal;
extern S_GAME_STARTDefaultTypeInternal _S_GAME_START_default_instance_;
class S_LOGIN;
struct S_LOGINDefaultTypeInternal;
extern S_LOGINDefaultTypeInternal _S_LOGIN_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::C_CLIENT_READY* Arena::CreateMaybeMessage<::Protocol::C_CLIENT_READY>(Arena*);
template<> ::Protocol::C_DEBUG_COMMAND* Arena::CreateMaybeMessage<::Protocol::C_DEBUG_COMMAND>(Arena*);
template<> ::Protocol::C_ENTER_GAME* Arena::CreateMaybeMessage<::Protocol::C_ENTER_GAME>(Arena*);
template<> ::Protocol::C_GAME_START* Arena::CreateMaybeMessage<::Protocol::C_GAME_START>(Arena*);
template<> ::Protocol::C_INPUT* Arena::CreateMaybeMessage<::Protocol::C_INPUT>(Arena*);
template<> ::Protocol::C_LOGIN* Arena::CreateMaybeMessage<::Protocol::C_LOGIN>(Arena*);
template<> ::Protocol::S_ENTER_GAME* Arena::CreateMaybeMessage<::Protocol::S_ENTER_GAME>(Arena*);
template<> ::Protocol::S_FORCED_TRANSFORM* Arena::CreateMaybeMessage<::Protocol::S_FORCED_TRANSFORM>(Arena*);
template<> ::Protocol::S_FRAME_STATE* Arena::CreateMaybeMessage<::Protocol::S_FRAME_STATE>(Arena*);
template<> ::Protocol::S_GAME_START* Arena::CreateMaybeMessage<::Protocol::S_GAME_START>(Arena*);
template<> ::Protocol::S_LOGIN* Arena::CreateMaybeMessage<::Protocol::S_LOGIN>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class C_LOGIN final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.C_LOGIN) */ {
 public:
  inline C_LOGIN() : C_LOGIN(nullptr) {}
  ~C_LOGIN() override;
  explicit constexpr C_LOGIN(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_LOGIN(const C_LOGIN& from);
  C_LOGIN(C_LOGIN&& from) noexcept
    : C_LOGIN() {
    *this = ::std::move(from);
  }

  inline C_LOGIN& operator=(const C_LOGIN& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_LOGIN& operator=(C_LOGIN&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_LOGIN& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_LOGIN* internal_default_instance() {
    return reinterpret_cast<const C_LOGIN*>(
               &_C_LOGIN_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(C_LOGIN& a, C_LOGIN& b) {
    a.Swap(&b);
  }
  inline void Swap(C_LOGIN* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_LOGIN* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline C_LOGIN* New() const final {
    return new C_LOGIN();
  }

  C_LOGIN* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<C_LOGIN>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const C_LOGIN& from);
  void MergeFrom(const C_LOGIN& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C_LOGIN* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.C_LOGIN";
  }
  protected:
  explicit C_LOGIN(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Protocol.C_LOGIN)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_LOGIN final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_LOGIN) */ {
 public:
  inline S_LOGIN() : S_LOGIN(nullptr) {}
  ~S_LOGIN() override;
  explicit constexpr S_LOGIN(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_LOGIN(const S_LOGIN& from);
  S_LOGIN(S_LOGIN&& from) noexcept
    : S_LOGIN() {
    *this = ::std::move(from);
  }

  inline S_LOGIN& operator=(const S_LOGIN& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_LOGIN& operator=(S_LOGIN&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_LOGIN& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_LOGIN* internal_default_instance() {
    return reinterpret_cast<const S_LOGIN*>(
               &_S_LOGIN_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(S_LOGIN& a, S_LOGIN& b) {
    a.Swap(&b);
  }
  inline void Swap(S_LOGIN* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_LOGIN* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline S_LOGIN* New() const final {
    return new S_LOGIN();
  }

  S_LOGIN* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<S_LOGIN>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const S_LOGIN& from);
  void MergeFrom(const S_LOGIN& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_LOGIN* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_LOGIN";
  }
  protected:
  explicit S_LOGIN(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayersFieldNumber = 2,
    kSuccessFieldNumber = 1,
    kPlayerIdFieldNumber = 3,
  };
  // repeated .Protocol.Player players = 2;
  int players_size() const;
  private:
  int _internal_players_size() const;
  public:
  void clear_players();
  ::Protocol::Player* mutable_players(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Player >*
      mutable_players();
  private:
  const ::Protocol::Player& _internal_players(int index) const;
  ::Protocol::Player* _internal_add_players();
  public:
  const ::Protocol::Player& players(int index) const;
  ::Protocol::Player* add_players();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Player >&
      players() const;

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // uint32 playerId = 3;
  void clear_playerid();
  ::PROTOBUF_NAMESPACE_ID::uint32 playerid() const;
  void set_playerid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_playerid() const;
  void _internal_set_playerid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S_LOGIN)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Player > players_;
  bool success_;
  ::PROTOBUF_NAMESPACE_ID::uint32 playerid_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class C_ENTER_GAME final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.C_ENTER_GAME) */ {
 public:
  inline C_ENTER_GAME() : C_ENTER_GAME(nullptr) {}
  ~C_ENTER_GAME() override;
  explicit constexpr C_ENTER_GAME(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_ENTER_GAME(const C_ENTER_GAME& from);
  C_ENTER_GAME(C_ENTER_GAME&& from) noexcept
    : C_ENTER_GAME() {
    *this = ::std::move(from);
  }

  inline C_ENTER_GAME& operator=(const C_ENTER_GAME& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_ENTER_GAME& operator=(C_ENTER_GAME&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_ENTER_GAME& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_ENTER_GAME* internal_default_instance() {
    return reinterpret_cast<const C_ENTER_GAME*>(
               &_C_ENTER_GAME_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(C_ENTER_GAME& a, C_ENTER_GAME& b) {
    a.Swap(&b);
  }
  inline void Swap(C_ENTER_GAME* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_ENTER_GAME* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline C_ENTER_GAME* New() const final {
    return new C_ENTER_GAME();
  }

  C_ENTER_GAME* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<C_ENTER_GAME>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const C_ENTER_GAME& from);
  void MergeFrom(const C_ENTER_GAME& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C_ENTER_GAME* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.C_ENTER_GAME";
  }
  protected:
  explicit C_ENTER_GAME(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerIdFieldNumber = 1,
    kPlayerWeaponFieldNumber = 2,
    kReadyFieldNumber = 3,
  };
  // uint64 playerId = 1;
  void clear_playerid();
  ::PROTOBUF_NAMESPACE_ID::uint64 playerid() const;
  void set_playerid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_playerid() const;
  void _internal_set_playerid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint32 playerWeapon = 2;
  void clear_playerweapon();
  ::PROTOBUF_NAMESPACE_ID::uint32 playerweapon() const;
  void set_playerweapon(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_playerweapon() const;
  void _internal_set_playerweapon(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // bool ready = 3;
  void clear_ready();
  bool ready() const;
  void set_ready(bool value);
  private:
  bool _internal_ready() const;
  void _internal_set_ready(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.C_ENTER_GAME)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint64 playerid_;
  ::PROTOBUF_NAMESPACE_ID::uint32 playerweapon_;
  bool ready_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_ENTER_GAME final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_ENTER_GAME) */ {
 public:
  inline S_ENTER_GAME() : S_ENTER_GAME(nullptr) {}
  ~S_ENTER_GAME() override;
  explicit constexpr S_ENTER_GAME(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_ENTER_GAME(const S_ENTER_GAME& from);
  S_ENTER_GAME(S_ENTER_GAME&& from) noexcept
    : S_ENTER_GAME() {
    *this = ::std::move(from);
  }

  inline S_ENTER_GAME& operator=(const S_ENTER_GAME& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_ENTER_GAME& operator=(S_ENTER_GAME&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_ENTER_GAME& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_ENTER_GAME* internal_default_instance() {
    return reinterpret_cast<const S_ENTER_GAME*>(
               &_S_ENTER_GAME_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(S_ENTER_GAME& a, S_ENTER_GAME& b) {
    a.Swap(&b);
  }
  inline void Swap(S_ENTER_GAME* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_ENTER_GAME* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline S_ENTER_GAME* New() const final {
    return new S_ENTER_GAME();
  }

  S_ENTER_GAME* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<S_ENTER_GAME>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const S_ENTER_GAME& from);
  void MergeFrom(const S_ENTER_GAME& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_ENTER_GAME* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_ENTER_GAME";
  }
  protected:
  explicit S_ENTER_GAME(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayersFieldNumber = 1,
    kReadyFieldNumber = 2,
  };
  // repeated .Protocol.Player players = 1;
  int players_size() const;
  private:
  int _internal_players_size() const;
  public:
  void clear_players();
  ::Protocol::Player* mutable_players(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Player >*
      mutable_players();
  private:
  const ::Protocol::Player& _internal_players(int index) const;
  ::Protocol::Player* _internal_add_players();
  public:
  const ::Protocol::Player& players(int index) const;
  ::Protocol::Player* add_players();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Player >&
      players() const;

  // repeated bool ready = 2;
  int ready_size() const;
  private:
  int _internal_ready_size() const;
  public:
  void clear_ready();
  private:
  bool _internal_ready(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool >&
      _internal_ready() const;
  void _internal_add_ready(bool value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool >*
      _internal_mutable_ready();
  public:
  bool ready(int index) const;
  void set_ready(int index, bool value);
  void add_ready(bool value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool >&
      ready() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool >*
      mutable_ready();

  // @@protoc_insertion_point(class_scope:Protocol.S_ENTER_GAME)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Player > players_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool > ready_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class C_GAME_START final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.C_GAME_START) */ {
 public:
  inline C_GAME_START() : C_GAME_START(nullptr) {}
  ~C_GAME_START() override;
  explicit constexpr C_GAME_START(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_GAME_START(const C_GAME_START& from);
  C_GAME_START(C_GAME_START&& from) noexcept
    : C_GAME_START() {
    *this = ::std::move(from);
  }

  inline C_GAME_START& operator=(const C_GAME_START& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_GAME_START& operator=(C_GAME_START&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_GAME_START& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_GAME_START* internal_default_instance() {
    return reinterpret_cast<const C_GAME_START*>(
               &_C_GAME_START_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(C_GAME_START& a, C_GAME_START& b) {
    a.Swap(&b);
  }
  inline void Swap(C_GAME_START* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_GAME_START* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline C_GAME_START* New() const final {
    return new C_GAME_START();
  }

  C_GAME_START* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<C_GAME_START>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const C_GAME_START& from);
  void MergeFrom(const C_GAME_START& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C_GAME_START* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.C_GAME_START";
  }
  protected:
  explicit C_GAME_START(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerIdFieldNumber = 1,
    kPlayerWeaponFieldNumber = 2,
    kReadyFieldNumber = 3,
  };
  // uint32 playerId = 1;
  void clear_playerid();
  ::PROTOBUF_NAMESPACE_ID::uint32 playerid() const;
  void set_playerid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_playerid() const;
  void _internal_set_playerid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 playerWeapon = 2;
  void clear_playerweapon();
  ::PROTOBUF_NAMESPACE_ID::uint32 playerweapon() const;
  void set_playerweapon(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_playerweapon() const;
  void _internal_set_playerweapon(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // bool ready = 3;
  void clear_ready();
  bool ready() const;
  void set_ready(bool value);
  private:
  bool _internal_ready() const;
  void _internal_set_ready(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.C_GAME_START)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint32 playerid_;
  ::PROTOBUF_NAMESPACE_ID::uint32 playerweapon_;
  bool ready_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_GAME_START final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_GAME_START) */ {
 public:
  inline S_GAME_START() : S_GAME_START(nullptr) {}
  ~S_GAME_START() override;
  explicit constexpr S_GAME_START(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_GAME_START(const S_GAME_START& from);
  S_GAME_START(S_GAME_START&& from) noexcept
    : S_GAME_START() {
    *this = ::std::move(from);
  }

  inline S_GAME_START& operator=(const S_GAME_START& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_GAME_START& operator=(S_GAME_START&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_GAME_START& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_GAME_START* internal_default_instance() {
    return reinterpret_cast<const S_GAME_START*>(
               &_S_GAME_START_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(S_GAME_START& a, S_GAME_START& b) {
    a.Swap(&b);
  }
  inline void Swap(S_GAME_START* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_GAME_START* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline S_GAME_START* New() const final {
    return new S_GAME_START();
  }

  S_GAME_START* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<S_GAME_START>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const S_GAME_START& from);
  void MergeFrom(const S_GAME_START& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_GAME_START* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_GAME_START";
  }
  protected:
  explicit S_GAME_START(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMapIdFieldNumber = 2,
    kInitStructFieldNumber = 1,
  };
  // string mapId = 2;
  void clear_mapid();
  const std::string& mapid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_mapid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_mapid();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_mapid();
  void set_allocated_mapid(std::string* mapid);
  private:
  const std::string& _internal_mapid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_mapid(const std::string& value);
  std::string* _internal_mutable_mapid();
  public:

  // .Protocol.InitStruct initStruct = 1;
  bool has_initstruct() const;
  private:
  bool _internal_has_initstruct() const;
  public:
  void clear_initstruct();
  const ::Protocol::InitStruct& initstruct() const;
  PROTOBUF_FUTURE_MUST_USE_RESULT ::Protocol::InitStruct* release_initstruct();
  ::Protocol::InitStruct* mutable_initstruct();
  void set_allocated_initstruct(::Protocol::InitStruct* initstruct);
  private:
  const ::Protocol::InitStruct& _internal_initstruct() const;
  ::Protocol::InitStruct* _internal_mutable_initstruct();
  public:
  void unsafe_arena_set_allocated_initstruct(
      ::Protocol::InitStruct* initstruct);
  ::Protocol::InitStruct* unsafe_arena_release_initstruct();

  // @@protoc_insertion_point(class_scope:Protocol.S_GAME_START)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr mapid_;
  ::Protocol::InitStruct* initstruct_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class C_CLIENT_READY final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.C_CLIENT_READY) */ {
 public:
  inline C_CLIENT_READY() : C_CLIENT_READY(nullptr) {}
  ~C_CLIENT_READY() override;
  explicit constexpr C_CLIENT_READY(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_CLIENT_READY(const C_CLIENT_READY& from);
  C_CLIENT_READY(C_CLIENT_READY&& from) noexcept
    : C_CLIENT_READY() {
    *this = ::std::move(from);
  }

  inline C_CLIENT_READY& operator=(const C_CLIENT_READY& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_CLIENT_READY& operator=(C_CLIENT_READY&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_CLIENT_READY& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_CLIENT_READY* internal_default_instance() {
    return reinterpret_cast<const C_CLIENT_READY*>(
               &_C_CLIENT_READY_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(C_CLIENT_READY& a, C_CLIENT_READY& b) {
    a.Swap(&b);
  }
  inline void Swap(C_CLIENT_READY* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_CLIENT_READY* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline C_CLIENT_READY* New() const final {
    return new C_CLIENT_READY();
  }

  C_CLIENT_READY* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<C_CLIENT_READY>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const C_CLIENT_READY& from);
  void MergeFrom(const C_CLIENT_READY& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C_CLIENT_READY* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.C_CLIENT_READY";
  }
  protected:
  explicit C_CLIENT_READY(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerIdFieldNumber = 1,
    kReadyFieldNumber = 2,
  };
  // uint32 playerId = 1;
  void clear_playerid();
  ::PROTOBUF_NAMESPACE_ID::uint32 playerid() const;
  void set_playerid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_playerid() const;
  void _internal_set_playerid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // bool ready = 2;
  void clear_ready();
  bool ready() const;
  void set_ready(bool value);
  private:
  bool _internal_ready() const;
  void _internal_set_ready(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.C_CLIENT_READY)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint32 playerid_;
  bool ready_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class C_INPUT final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.C_INPUT) */ {
 public:
  inline C_INPUT() : C_INPUT(nullptr) {}
  ~C_INPUT() override;
  explicit constexpr C_INPUT(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_INPUT(const C_INPUT& from);
  C_INPUT(C_INPUT&& from) noexcept
    : C_INPUT() {
    *this = ::std::move(from);
  }

  inline C_INPUT& operator=(const C_INPUT& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_INPUT& operator=(C_INPUT&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_INPUT& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_INPUT* internal_default_instance() {
    return reinterpret_cast<const C_INPUT*>(
               &_C_INPUT_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(C_INPUT& a, C_INPUT& b) {
    a.Swap(&b);
  }
  inline void Swap(C_INPUT* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_INPUT* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline C_INPUT* New() const final {
    return new C_INPUT();
  }

  C_INPUT* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<C_INPUT>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const C_INPUT& from);
  void MergeFrom(const C_INPUT& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C_INPUT* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.C_INPUT";
  }
  protected:
  explicit C_INPUT(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayeridFieldNumber = 1,
    kKeyCodesFieldNumber = 2,
    kDeltaXFieldNumber = 3,
    kDeltaYFieldNumber = 4,
    kClientDeltaTimeFieldNumber = 5,
  };
  // uint64 playerid = 1;
  void clear_playerid();
  ::PROTOBUF_NAMESPACE_ID::uint64 playerid() const;
  void set_playerid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_playerid() const;
  void _internal_set_playerid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // int32 keyCodes = 2;
  void clear_keycodes();
  ::PROTOBUF_NAMESPACE_ID::int32 keycodes() const;
  void set_keycodes(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_keycodes() const;
  void _internal_set_keycodes(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // float deltaX = 3;
  void clear_deltax();
  float deltax() const;
  void set_deltax(float value);
  private:
  float _internal_deltax() const;
  void _internal_set_deltax(float value);
  public:

  // float deltaY = 4;
  void clear_deltay();
  float deltay() const;
  void set_deltay(float value);
  private:
  float _internal_deltay() const;
  void _internal_set_deltay(float value);
  public:

  // float clientDeltaTime = 5;
  void clear_clientdeltatime();
  float clientdeltatime() const;
  void set_clientdeltatime(float value);
  private:
  float _internal_clientdeltatime() const;
  void _internal_set_clientdeltatime(float value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.C_INPUT)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint64 playerid_;
  ::PROTOBUF_NAMESPACE_ID::int32 keycodes_;
  float deltax_;
  float deltay_;
  float clientdeltatime_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_FRAME_STATE final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_FRAME_STATE) */ {
 public:
  inline S_FRAME_STATE() : S_FRAME_STATE(nullptr) {}
  ~S_FRAME_STATE() override;
  explicit constexpr S_FRAME_STATE(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_FRAME_STATE(const S_FRAME_STATE& from);
  S_FRAME_STATE(S_FRAME_STATE&& from) noexcept
    : S_FRAME_STATE() {
    *this = ::std::move(from);
  }

  inline S_FRAME_STATE& operator=(const S_FRAME_STATE& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_FRAME_STATE& operator=(S_FRAME_STATE&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_FRAME_STATE& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_FRAME_STATE* internal_default_instance() {
    return reinterpret_cast<const S_FRAME_STATE*>(
               &_S_FRAME_STATE_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(S_FRAME_STATE& a, S_FRAME_STATE& b) {
    a.Swap(&b);
  }
  inline void Swap(S_FRAME_STATE* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_FRAME_STATE* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline S_FRAME_STATE* New() const final {
    return new S_FRAME_STATE();
  }

  S_FRAME_STATE* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<S_FRAME_STATE>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const S_FRAME_STATE& from);
  void MergeFrom(const S_FRAME_STATE& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_FRAME_STATE* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_FRAME_STATE";
  }
  protected:
  explicit S_FRAME_STATE(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayersFieldNumber = 2,
    kEnemiesFieldNumber = 3,
    kBulletsFieldNumber = 4,
    kServerTickFieldNumber = 1,
    kBossRoomStateFieldNumber = 5,
  };
  // repeated .Protocol.Player players = 2;
  int players_size() const;
  private:
  int _internal_players_size() const;
  public:
  void clear_players();
  ::Protocol::Player* mutable_players(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Player >*
      mutable_players();
  private:
  const ::Protocol::Player& _internal_players(int index) const;
  ::Protocol::Player* _internal_add_players();
  public:
  const ::Protocol::Player& players(int index) const;
  ::Protocol::Player* add_players();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Player >&
      players() const;

  // repeated .Protocol.Enemy enemies = 3;
  int enemies_size() const;
  private:
  int _internal_enemies_size() const;
  public:
  void clear_enemies();
  ::Protocol::Enemy* mutable_enemies(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Enemy >*
      mutable_enemies();
  private:
  const ::Protocol::Enemy& _internal_enemies(int index) const;
  ::Protocol::Enemy* _internal_add_enemies();
  public:
  const ::Protocol::Enemy& enemies(int index) const;
  ::Protocol::Enemy* add_enemies();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Enemy >&
      enemies() const;

  // repeated .Protocol.Bullet bullets = 4;
  int bullets_size() const;
  private:
  int _internal_bullets_size() const;
  public:
  void clear_bullets();
  ::Protocol::Bullet* mutable_bullets(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Bullet >*
      mutable_bullets();
  private:
  const ::Protocol::Bullet& _internal_bullets(int index) const;
  ::Protocol::Bullet* _internal_add_bullets();
  public:
  const ::Protocol::Bullet& bullets(int index) const;
  ::Protocol::Bullet* add_bullets();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Bullet >&
      bullets() const;

  // uint32 serverTick = 1;
  void clear_servertick();
  ::PROTOBUF_NAMESPACE_ID::uint32 servertick() const;
  void set_servertick(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_servertick() const;
  void _internal_set_servertick(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // .Protocol.BossRoomState bossRoomState = 5;
  void clear_bossroomstate();
  ::Protocol::BossRoomState bossroomstate() const;
  void set_bossroomstate(::Protocol::BossRoomState value);
  private:
  ::Protocol::BossRoomState _internal_bossroomstate() const;
  void _internal_set_bossroomstate(::Protocol::BossRoomState value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S_FRAME_STATE)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Player > players_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Enemy > enemies_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Bullet > bullets_;
  ::PROTOBUF_NAMESPACE_ID::uint32 servertick_;
  int bossroomstate_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_FORCED_TRANSFORM final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_FORCED_TRANSFORM) */ {
 public:
  inline S_FORCED_TRANSFORM() : S_FORCED_TRANSFORM(nullptr) {}
  ~S_FORCED_TRANSFORM() override;
  explicit constexpr S_FORCED_TRANSFORM(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_FORCED_TRANSFORM(const S_FORCED_TRANSFORM& from);
  S_FORCED_TRANSFORM(S_FORCED_TRANSFORM&& from) noexcept
    : S_FORCED_TRANSFORM() {
    *this = ::std::move(from);
  }

  inline S_FORCED_TRANSFORM& operator=(const S_FORCED_TRANSFORM& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_FORCED_TRANSFORM& operator=(S_FORCED_TRANSFORM&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_FORCED_TRANSFORM& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_FORCED_TRANSFORM* internal_default_instance() {
    return reinterpret_cast<const S_FORCED_TRANSFORM*>(
               &_S_FORCED_TRANSFORM_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  friend void swap(S_FORCED_TRANSFORM& a, S_FORCED_TRANSFORM& b) {
    a.Swap(&b);
  }
  inline void Swap(S_FORCED_TRANSFORM* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_FORCED_TRANSFORM* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline S_FORCED_TRANSFORM* New() const final {
    return new S_FORCED_TRANSFORM();
  }

  S_FORCED_TRANSFORM* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<S_FORCED_TRANSFORM>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const S_FORCED_TRANSFORM& from);
  void MergeFrom(const S_FORCED_TRANSFORM& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_FORCED_TRANSFORM* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_FORCED_TRANSFORM";
  }
  protected:
  explicit S_FORCED_TRANSFORM(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerIdFieldNumber = 1,
    kYawDeltaFieldNumber = 2,
    kReasonFieldNumber = 3,
  };
  // uint64 playerId = 1;
  void clear_playerid();
  ::PROTOBUF_NAMESPACE_ID::uint64 playerid() const;
  void set_playerid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_playerid() const;
  void _internal_set_playerid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // float yawDelta = 2;
  void clear_yawdelta();
  float yawdelta() const;
  void set_yawdelta(float value);
  private:
  float _internal_yawdelta() const;
  void _internal_set_yawdelta(float value);
  public:

  // .Protocol.ForcedTransformReason reason = 3;
  void clear_reason();
  ::Protocol::ForcedTransformReason reason() const;
  void set_reason(::Protocol::ForcedTransformReason value);
  private:
  ::Protocol::ForcedTransformReason _internal_reason() const;
  void _internal_set_reason(::Protocol::ForcedTransformReason value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S_FORCED_TRANSFORM)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint64 playerid_;
  float yawdelta_;
  int reason_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class C_DEBUG_COMMAND final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.C_DEBUG_COMMAND) */ {
 public:
  inline C_DEBUG_COMMAND() : C_DEBUG_COMMAND(nullptr) {}
  ~C_DEBUG_COMMAND() override;
  explicit constexpr C_DEBUG_COMMAND(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_DEBUG_COMMAND(const C_DEBUG_COMMAND& from);
  C_DEBUG_COMMAND(C_DEBUG_COMMAND&& from) noexcept
    : C_DEBUG_COMMAND() {
    *this = ::std::move(from);
  }

  inline C_DEBUG_COMMAND& operator=(const C_DEBUG_COMMAND& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_DEBUG_COMMAND& operator=(C_DEBUG_COMMAND&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_DEBUG_COMMAND& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_DEBUG_COMMAND* internal_default_instance() {
    return reinterpret_cast<const C_DEBUG_COMMAND*>(
               &_C_DEBUG_COMMAND_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    10;

  friend void swap(C_DEBUG_COMMAND& a, C_DEBUG_COMMAND& b) {
    a.Swap(&b);
  }
  inline void Swap(C_DEBUG_COMMAND* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_DEBUG_COMMAND* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline C_DEBUG_COMMAND* New() const final {
    return new C_DEBUG_COMMAND();
  }

  C_DEBUG_COMMAND* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<C_DEBUG_COMMAND>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const C_DEBUG_COMMAND& from);
  void MergeFrom(const C_DEBUG_COMMAND& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C_DEBUG_COMMAND* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.C_DEBUG_COMMAND";
  }
  protected:
  explicit C_DEBUG_COMMAND(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCommandTypeFieldNumber = 1,
    kMegaGridNumberFieldNumber = 2,
  };
  // .Protocol.DebugCommandType commandType = 1;
  void clear_commandtype();
  ::Protocol::DebugCommandType commandtype() const;
  void set_commandtype(::Protocol::DebugCommandType value);
  private:
  ::Protocol::DebugCommandType _internal_commandtype() const;
  void _internal_set_commandtype(::Protocol::DebugCommandType value);
  public:

  // int32 megaGridNumber = 2;
  void clear_megagridnumber();
  ::PROTOBUF_NAMESPACE_ID::int32 megagridnumber() const;
  void set_megagridnumber(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_megagridnumber() const;
  void _internal_set_megagridnumber(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.C_DEBUG_COMMAND)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int commandtype_;
  ::PROTOBUF_NAMESPACE_ID::int32 megagridnumber_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// C_LOGIN

// -------------------------------------------------------------------

// S_LOGIN

// bool success = 1;
inline void S_LOGIN::clear_success() {
  success_ = false;
}
inline bool S_LOGIN::_internal_success() const {
  return success_;
}
inline bool S_LOGIN::success() const {
  // @@protoc_insertion_point(field_get:Protocol.S_LOGIN.success)
  return _internal_success();
}
inline void S_LOGIN::_internal_set_success(bool value) {
  
  success_ = value;
}
inline void S_LOGIN::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:Protocol.S_LOGIN.success)
}

// repeated .Protocol.Player players = 2;
inline int S_LOGIN::_internal_players_size() const {
  return players_.size();
}
inline int S_LOGIN::players_size() const {
  return _internal_players_size();
}
inline ::Protocol::Player* S_LOGIN::mutable_players(int index) {
  // @@protoc_insertion_point(field_mutable:Protocol.S_LOGIN.players)
  return players_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Player >*
S_LOGIN::mutable_players() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.S_LOGIN.players)
  return &players_;
}
inline const ::Protocol::Player& S_LOGIN::_internal_players(int index) const {
  return players_.Get(index);
}
inline const ::Protocol::Player& S_LOGIN::players(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.S_LOGIN.players)
  return _internal_players(index);
}
inline ::Protocol::Player* S_LOGIN::_internal_add_players() {
  return players_.Add();
}
inline ::Protocol::Player* S_LOGIN::add_players() {
  // @@protoc_insertion_point(field_add:Protocol.S_LOGIN.players)
  return _internal_add_players();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Player >&
S_LOGIN::players() const {
  // @@protoc_insertion_point(field_list:Protocol.S_LOGIN.players)
  return players_;
}

// uint32 playerId = 3;
inline void S_LOGIN::clear_playerid() {
  playerid_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 S_LOGIN::_internal_playerid() const {
  return playerid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 S_LOGIN::playerid() const {
  // @@protoc_insertion_point(field_get:Protocol.S_LOGIN.playerId)
  return _internal_playerid();
}
inline void S_LOGIN::_internal_set_playerid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  playerid_ = value;
}
inline void S_LOGIN::set_playerid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_playerid(value);
  // @@protoc_insertion_point(field_set:Protocol.S_LOGIN.playerId)
}

// -------------------------------------------------------------------

// C_ENTER_GAME

// uint64 playerId = 1;
inline void C_ENTER_GAME::clear_playerid() {
  playerid_ = uint64_t{0u};
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 C_ENTER_GAME::_internal_playerid() const {
  return playerid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 C_ENTER_GAME::playerid() const {
  // @@protoc_insertion_point(field_get:Protocol.C_ENTER_GAME.playerId)
  return _internal_playerid();
}
inline void C_ENTER_GAME::_internal_set_playerid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  playerid_ = value;
}
inline void C_ENTER_GAME::set_playerid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_playerid(value);
  // @@protoc_insertion_point(field_set:Protocol.C_ENTER_GAME.playerId)
}

// uint32 playerWeapon = 2;
inline void C_ENTER_GAME::clear_playerweapon() {
  playerweapon_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 C_ENTER_GAME::_internal_playerweapon() const {
  return playerweapon_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 C_ENTER_GAME::playerweapon() const {
  // @@protoc_insertion_point(field_get:Protocol.C_ENTER_GAME.playerWeapon)
  return _internal_playerweapon();
}
inline void C_ENTER_GAME::_internal_set_playerweapon(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  playerweapon_ = value;
}
inline void C_ENTER_GAME::set_playerweapon(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_playerweapon(value);
  // @@protoc_insertion_point(field_set:Protocol.C_ENTER_GAME.playerWeapon)
}

// bool ready = 3;
inline void C_ENTER_GAME::clear_ready() {
  ready_ = false;
}
inline bool C_ENTER_GAME::_internal_ready() const {
  return ready_;
}
inline bool C_ENTER_GAME::ready() const {
  // @@protoc_insertion_point(field_get:Protocol.C_ENTER_GAME.ready)
  return _internal_ready();
}
inline void C_ENTER_GAME::_internal_set_ready(bool value) {
  
  ready_ = value;
}
inline void C_ENTER_GAME::set_ready(bool value) {
  _internal_set_ready(value);
  // @@protoc_insertion_point(field_set:Protocol.C_ENTER_GAME.ready)
}

// -------------------------------------------------------------------

// S_ENTER_GAME

// repeated .Protocol.Player players = 1;
inline int S_ENTER_GAME::_internal_players_size() const {
  return players_.size();
}
inline int S_ENTER_GAME::players_size() const {
  return _internal_players_size();
}
inline ::Protocol::Player* S_ENTER_GAME::mutable_players(int index) {
  // @@protoc_insertion_point(field_mutable:Protocol.S_ENTER_GAME.players)
  return players_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Player >*
S_ENTER_GAME::mutable_players() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.S_ENTER_GAME.players)
  return &players_;
}
inline const ::Protocol::Player& S_ENTER_GAME::_internal_players(int index) const {
  return players_.Get(index);
}
inline const ::Protocol::Player& S_ENTER_GAME::players(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.S_ENTER_GAME.players)
  return _internal_players(index);
}
inline ::Protocol::Player* S_ENTER_GAME::_internal_add_players() {
  return players_.Add();
}
inline ::Protocol::Player* S_ENTER_GAME::add_players() {
  // @@protoc_insertion_point(field_add:Protocol.S_ENTER_GAME.players)
  return _internal_add_players();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Player >&
S_ENTER_GAME::players() const {
  // @@protoc_insertion_point(field_list:Protocol.S_ENTER_GAME.players)
  return players_;
}

// repeated bool ready = 2;
inline int S_ENTER_GAME::_internal_ready_size() const {
  return ready_.size();
}
inline int S_ENTER_GAME::ready_size() const {
  return _internal_ready_size();
}
inline void S_ENTER_GAME::clear_ready() {
  ready_.Clear();
}
inline bool S_ENTER_GAME::_internal_ready(int index) const {
  return ready_.Get(index);
}
inline bool S_ENTER_GAME::ready(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.S_ENTER_GAME.ready)
  return _internal_ready(index);
}
inline void S_ENTER_GAME::set_ready(int index, bool value) {
  ready_.Set(index, value);
  // @@protoc_insertion_point(field_set:Protocol.S_ENTER_GAME.ready)
}
inline void S_ENTER_GAME::_internal_add_ready(bool value) {
  ready_.Add(value);
}
inline void S_ENTER_GAME::add_ready(bool value) {
  _internal_add_ready(value);
  // @@protoc_insertion_point(field_add:Protocol.S_ENTER_GAME.ready)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool >&
S_ENTER_GAME::_internal_ready() const {
  return ready_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool >&
S_ENTER_GAME::ready() const {
  // @@protoc_insertion_point(field_list:Protocol.S_ENTER_GAME.ready)
  return _internal_ready();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool >*
S_ENTER_GAME::_internal_mutable_ready() {
  return &ready_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool >*
S_ENTER_GAME::mutable_ready() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.S_ENTER_GAME.ready)
  return _internal_mutable_ready();
}

// -------------------------------------------------------------------

// C_GAME_START

// uint32 playerId = 1;
inline void C_GAME_START::clear_playerid() {
  playerid_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 C_GAME_START::_internal_playerid() const {
  return playerid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 C_GAME_START::playerid() const {
  // @@protoc_insertion_point(field_get:Protocol.C_GAME_START.playerId)
  return _internal_playerid();
}
inline void C_GAME_START::_internal_set_playerid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  playerid_ = value;
}
inline void C_GAME_START::set_playerid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_playerid(value);
  // @@protoc_insertion_point(field_set:Protocol.C_GAME_START.playerId)
}

// uint32 playerWeapon = 2;
inline void C_GAME_START::clear_playerweapon() {
  playerweapon_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 C_GAME_START::_internal_playerweapon() const {
  return playerweapon_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 C_GAME_START::playerweapon() const {
  // @@protoc_insertion_point(field_get:Protocol.C_GAME_START.playerWeapon)
  return _internal_playerweapon();
}
inline void C_GAME_START::_internal_set_playerweapon(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  playerweapon_ = value;
}
inline void C_GAME_START::set_playerweapon(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_playerweapon(value);
  // @@protoc_insertion_point(field_set:Protocol.C_GAME_START.playerWeapon)
}

// bool ready = 3;
inline void C_GAME_START::clear_ready() {
  ready_ = false;
}
inline bool C_GAME_START::_internal_ready() const {
  return ready_;
}
inline bool C_GAME_START::ready() const {
  // @@protoc_insertion_point(field_get:Protocol.C_GAME_START.ready)
  return _internal_ready();
}
inline void C_GAME_START::_internal_set_ready(bool value) {
  
  ready_ = value;
}
inline void C_GAME_START::set_ready(bool value) {
  _internal_set_ready(value);
  // @@protoc_insertion_point(field_set:Protocol.C_GAME_START.ready)
}

// -------------------------------------------------------------------

// S_GAME_START

// .Protocol.InitStruct initStruct = 1;
inline bool S_GAME_START::_internal_has_initstruct() const {
  return this != internal_default_instance() && initstruct_ != nullptr;
}
inline bool S_GAME_START::has_initstruct() const {
  return _internal_has_initstruct();
}
inline const ::Protocol::InitStruct& S_GAME_START::_internal_initstruct() const {
  const ::Protocol::InitStruct* p = initstruct_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::InitStruct&>(
      ::Protocol::_InitStruct_default_instance_);
}
inline const ::Protocol::InitStruct& S_GAME_START::initstruct() const {
  // @@protoc_insertion_point(field_get:Protocol.S_GAME_START.initStruct)
  return _internal_initstruct();
}
inline void S_GAME_START::unsafe_arena_set_allocated_initstruct(
    ::Protocol::InitStruct* initstruct) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(initstruct_);
  }
  initstruct_ = initstruct;
  if (initstruct) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.S_GAME_START.initStruct)
}
inline ::Protocol::InitStruct* S_GAME_START::release_initstruct() {
  
  ::Protocol::InitStruct* temp = initstruct_;
  initstruct_ = nullptr;
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::Protocol::InitStruct* S_GAME_START::unsafe_arena_release_initstruct() {
  // @@protoc_insertion_point(field_release:Protocol.S_GAME_START.initStruct)
  
  ::Protocol::InitStruct* temp = initstruct_;
  initstruct_ = nullptr;
  return temp;
}
inline ::Protocol::InitStruct* S_GAME_START::_internal_mutable_initstruct() {
  
  if (initstruct_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::InitStruct>(GetArenaForAllocation());
    initstruct_ = p;
  }
  return initstruct_;
}
inline ::Protocol::InitStruct* S_GAME_START::mutable_initstruct() {
  // @@protoc_insertion_point(field_mutable:Protocol.S_GAME_START.initStruct)
  return _internal_mutable_initstruct();
}
inline void S_GAME_START::set_allocated_initstruct(::Protocol::InitStruct* initstruct) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(initstruct_);
  }
  if (initstruct) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(initstruct));
    if (message_arena != submessage_arena) {
      initstruct = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, initstruct, submessage_arena);
    }
    
  } else {
    
  }
  initstruct_ = initstruct;
  // @@protoc_insertion_point(field_set_allocated:Protocol.S_GAME_START.initStruct)
}

// string mapId = 2;
inline void S_GAME_START::clear_mapid() {
  mapid_.ClearToEmpty();
}
inline const std::string& S_GAME_START::mapid() const {
  // @@protoc_insertion_point(field_get:Protocol.S_GAME_START.mapId)
  return _internal_mapid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void S_GAME_START::set_mapid(ArgT0&& arg0, ArgT... args) {
 
 mapid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.S_GAME_START.mapId)
}
inline std::string* S_GAME_START::mutable_mapid() {
  // @@protoc_insertion_point(field_mutable:Protocol.S_GAME_START.mapId)
  return _internal_mutable_mapid();
}
inline const std::string& S_GAME_START::_internal_mapid() const {
  return mapid_.Get();
}
inline void S_GAME_START::_internal_set_mapid(const std::string& value) {
  
  mapid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* S_GAME_START::_internal_mutable_mapid() {
  
  return mapid_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* S_GAME_START::release_mapid() {
  // @@protoc_insertion_point(field_release:Protocol.S_GAME_START.mapId)
  return mapid_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void S_GAME_START::set_allocated_mapid(std::string* mapid) {
  if (mapid != nullptr) {
    
  } else {
    
  }
  mapid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), mapid,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:Protocol.S_GAME_START.mapId)
}

// -------------------------------------------------------------------

// C_CLIENT_READY

// uint32 playerId = 1;
inline void C_CLIENT_READY::clear_playerid() {
  playerid_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 C_CLIENT_READY::_internal_playerid() const {
  return playerid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 C_CLIENT_READY::playerid() const {
  // @@protoc_insertion_point(field_get:Protocol.C_CLIENT_READY.playerId)
  return _internal_playerid();
}
inline void C_CLIENT_READY::_internal_set_playerid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  playerid_ = value;
}
inline void C_CLIENT_READY::set_playerid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_playerid(value);
  // @@protoc_insertion_point(field_set:Protocol.C_CLIENT_READY.playerId)
}

// bool ready = 2;
inline void C_CLIENT_READY::clear_ready() {
  ready_ = false;
}
inline bool C_CLIENT_READY::_internal_ready() const {
  return ready_;
}
inline bool C_CLIENT_READY::ready() const {
  // @@protoc_insertion_point(field_get:Protocol.C_CLIENT_READY.ready)
  return _internal_ready();
}
inline void C_CLIENT_READY::_internal_set_ready(bool value) {
  
  ready_ = value;
}
inline void C_CLIENT_READY::set_ready(bool value) {
  _internal_set_ready(value);
  // @@protoc_insertion_point(field_set:Protocol.C_CLIENT_READY.ready)
}

// -------------------------------------------------------------------

// C_INPUT

// uint64 playerid = 1;
inline void C_INPUT::clear_playerid() {
  playerid_ = uint64_t{0u};
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 C_INPUT::_internal_playerid() const {
  return playerid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 C_INPUT::playerid() const {
  // @@protoc_insertion_point(field_get:Protocol.C_INPUT.playerid)
  return _internal_playerid();
}
inline void C_INPUT::_internal_set_playerid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  playerid_ = value;
}
inline void C_INPUT::set_playerid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_playerid(value);
  // @@protoc_insertion_point(field_set:Protocol.C_INPUT.playerid)
}

// int32 keyCodes = 2;
inline void C_INPUT::clear_keycodes() {
  keycodes_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 C_INPUT::_internal_keycodes() const {
  return keycodes_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 C_INPUT::keycodes() const {
  // @@protoc_insertion_point(field_get:Protocol.C_INPUT.keyCodes)
  return _internal_keycodes();
}
inline void C_INPUT::_internal_set_keycodes(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  keycodes_ = value;
}
inline void C_INPUT::set_keycodes(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_keycodes(value);
  // @@protoc_insertion_point(field_set:Protocol.C_INPUT.keyCodes)
}

// float deltaX = 3;
inline void C_INPUT::clear_deltax() {
  deltax_ = 0;
}
inline float C_INPUT::_internal_deltax() const {
  return deltax_;
}
inline float C_INPUT::deltax() const {
  // @@protoc_insertion_point(field_get:Protocol.C_INPUT.deltaX)
  return _internal_deltax();
}
inline void C_INPUT::_internal_set_deltax(float value) {
  
  deltax_ = value;
}
inline void C_INPUT::set_deltax(float value) {
  _internal_set_deltax(value);
  // @@protoc_insertion_point(field_set:Protocol.C_INPUT.deltaX)
}

// float deltaY = 4;
inline void C_INPUT::clear_deltay() {
  deltay_ = 0;
}
inline float C_INPUT::_internal_deltay() const {
  return deltay_;
}
inline float C_INPUT::deltay() const {
  // @@protoc_insertion_point(field_get:Protocol.C_INPUT.deltaY)
  return _internal_deltay();
}
inline void C_INPUT::_internal_set_deltay(float value) {
  
  deltay_ = value;
}
inline void C_INPUT::set_deltay(float value) {
  _internal_set_deltay(value);
  // @@protoc_insertion_point(field_set:Protocol.C_INPUT.deltaY)
}

// float clientDeltaTime = 5;
inline void C_INPUT::clear_clientdeltatime() {
  clientdeltatime_ = 0;
}
inline float C_INPUT::_internal_clientdeltatime() const {
  return clientdeltatime_;
}
inline float C_INPUT::clientdeltatime() const {
  // @@protoc_insertion_point(field_get:Protocol.C_INPUT.clientDeltaTime)
  return _internal_clientdeltatime();
}
inline void C_INPUT::_internal_set_clientdeltatime(float value) {
  
  clientdeltatime_ = value;
}
inline void C_INPUT::set_clientdeltatime(float value) {
  _internal_set_clientdeltatime(value);
  // @@protoc_insertion_point(field_set:Protocol.C_INPUT.clientDeltaTime)
}

// -------------------------------------------------------------------

// S_FRAME_STATE

// uint32 serverTick = 1;
inline void S_FRAME_STATE::clear_servertick() {
  servertick_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 S_FRAME_STATE::_internal_servertick() const {
  return servertick_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 S_FRAME_STATE::servertick() const {
  // @@protoc_insertion_point(field_get:Protocol.S_FRAME_STATE.serverTick)
  return _internal_servertick();
}
inline void S_FRAME_STATE::_internal_set_servertick(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  servertick_ = value;
}
inline void S_FRAME_STATE::set_servertick(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_servertick(value);
  // @@protoc_insertion_point(field_set:Protocol.S_FRAME_STATE.serverTick)
}

// repeated .Protocol.Player players = 2;
inline int S_FRAME_STATE::_internal_players_size() const {
  return players_.size();
}
inline int S_FRAME_STATE::players_size() const {
  return _internal_players_size();
}
inline ::Protocol::Player* S_FRAME_STATE::mutable_players(int index) {
  // @@protoc_insertion_point(field_mutable:Protocol.S_FRAME_STATE.players)
  return players_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Player >*
S_FRAME_STATE::mutable_players() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.S_FRAME_STATE.players)
  return &players_;
}
inline const ::Protocol::Player& S_FRAME_STATE::_internal_players(int index) const {
  return players_.Get(index);
}
inline const ::Protocol::Player& S_FRAME_STATE::players(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.S_FRAME_STATE.players)
  return _internal_players(index);
}
inline ::Protocol::Player* S_FRAME_STATE::_internal_add_players() {
  return players_.Add();
}
inline ::Protocol::Player* S_FRAME_STATE::add_players() {
  // @@protoc_insertion_point(field_add:Protocol.S_FRAME_STATE.players)
  return _internal_add_players();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Player >&
S_FRAME_STATE::players() const {
  // @@protoc_insertion_point(field_list:Protocol.S_FRAME_STATE.players)
  return players_;
}

// repeated .Protocol.Enemy enemies = 3;
inline int S_FRAME_STATE::_internal_enemies_size() const {
  return enemies_.size();
}
inline int S_FRAME_STATE::enemies_size() const {
  return _internal_enemies_size();
}
inline ::Protocol::Enemy* S_FRAME_STATE::mutable_enemies(int index) {
  // @@protoc_insertion_point(field_mutable:Protocol.S_FRAME_STATE.enemies)
  return enemies_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Enemy >*
S_FRAME_STATE::mutable_enemies() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.S_FRAME_STATE.enemies)
  return &enemies_;
}
inline const ::Protocol::Enemy& S_FRAME_STATE::_internal_enemies(int index) const {
  return enemies_.Get(index);
}
inline const ::Protocol::Enemy& S_FRAME_STATE::enemies(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.S_FRAME_STATE.enemies)
  return _internal_enemies(index);
}
inline ::Protocol::Enemy* S_FRAME_STATE::_internal_add_enemies() {
  return enemies_.Add();
}
inline ::Protocol::Enemy* S_FRAME_STATE::add_enemies() {
  // @@protoc_insertion_point(field_add:Protocol.S_FRAME_STATE.enemies)
  return _internal_add_enemies();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Enemy >&
S_FRAME_STATE::enemies() const {
  // @@protoc_insertion_point(field_list:Protocol.S_FRAME_STATE.enemies)
  return enemies_;
}

// repeated .Protocol.Bullet bullets = 4;
inline int S_FRAME_STATE::_internal_bullets_size() const {
  return bullets_.size();
}
inline int S_FRAME_STATE::bullets_size() const {
  return _internal_bullets_size();
}
inline ::Protocol::Bullet* S_FRAME_STATE::mutable_bullets(int index) {
  // @@protoc_insertion_point(field_mutable:Protocol.S_FRAME_STATE.bullets)
  return bullets_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Bullet >*
S_FRAME_STATE::mutable_bullets() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.S_FRAME_STATE.bullets)
  return &bullets_;
}
inline const ::Protocol::Bullet& S_FRAME_STATE::_internal_bullets(int index) const {
  return bullets_.Get(index);
}
inline const ::Protocol::Bullet& S_FRAME_STATE::bullets(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.S_FRAME_STATE.bullets)
  return _internal_bullets(index);
}
inline ::Protocol::Bullet* S_FRAME_STATE::_internal_add_bullets() {
  return bullets_.Add();
}
inline ::Protocol::Bullet* S_FRAME_STATE::add_bullets() {
  // @@protoc_insertion_point(field_add:Protocol.S_FRAME_STATE.bullets)
  return _internal_add_bullets();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Bullet >&
S_FRAME_STATE::bullets() const {
  // @@protoc_insertion_point(field_list:Protocol.S_FRAME_STATE.bullets)
  return bullets_;
}

// .Protocol.BossRoomState bossRoomState = 5;
inline void S_FRAME_STATE::clear_bossroomstate() {
  bossroomstate_ = 0;
}
inline ::Protocol::BossRoomState S_FRAME_STATE::_internal_bossroomstate() const {
  return static_cast< ::Protocol::BossRoomState >(bossroomstate_);
}
inline ::Protocol::BossRoomState S_FRAME_STATE::bossroomstate() const {
  // @@protoc_insertion_point(field_get:Protocol.S_FRAME_STATE.bossRoomState)
  return _internal_bossroomstate();
}
inline void S_FRAME_STATE::_internal_set_bossroomstate(::Protocol::BossRoomState value) {
  
  bossroomstate_ = value;
}
inline void S_FRAME_STATE::set_bossroomstate(::Protocol::BossRoomState value) {
  _internal_set_bossroomstate(value);
  // @@protoc_insertion_point(field_set:Protocol.S_FRAME_STATE.bossRoomState)
}

// -------------------------------------------------------------------

// S_FORCED_TRANSFORM

// uint64 playerId = 1;
inline void S_FORCED_TRANSFORM::clear_playerid() {
  playerid_ = uint64_t{0u};
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 S_FORCED_TRANSFORM::_internal_playerid() const {
  return playerid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 S_FORCED_TRANSFORM::playerid() const {
  // @@protoc_insertion_point(field_get:Protocol.S_FORCED_TRANSFORM.playerId)
  return _internal_playerid();
}
inline void S_FORCED_TRANSFORM::_internal_set_playerid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  playerid_ = value;
}
inline void S_FORCED_TRANSFORM::set_playerid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_playerid(value);
  // @@protoc_insertion_point(field_set:Protocol.S_FORCED_TRANSFORM.playerId)
}

// float yawDelta = 2;
inline void S_FORCED_TRANSFORM::clear_yawdelta() {
  yawdelta_ = 0;
}
inline float S_FORCED_TRANSFORM::_internal_yawdelta() const {
  return yawdelta_;
}
inline float S_FORCED_TRANSFORM::yawdelta() const {
  // @@protoc_insertion_point(field_get:Protocol.S_FORCED_TRANSFORM.yawDelta)
  return _internal_yawdelta();
}
inline void S_FORCED_TRANSFORM::_internal_set_yawdelta(float value) {
  
  yawdelta_ = value;
}
inline void S_FORCED_TRANSFORM::set_yawdelta(float value) {
  _internal_set_yawdelta(value);
  // @@protoc_insertion_point(field_set:Protocol.S_FORCED_TRANSFORM.yawDelta)
}

// .Protocol.ForcedTransformReason reason = 3;
inline void S_FORCED_TRANSFORM::clear_reason() {
  reason_ = 0;
}
inline ::Protocol::ForcedTransformReason S_FORCED_TRANSFORM::_internal_reason() const {
  return static_cast< ::Protocol::ForcedTransformReason >(reason_);
}
inline ::Protocol::ForcedTransformReason S_FORCED_TRANSFORM::reason() const {
  // @@protoc_insertion_point(field_get:Protocol.S_FORCED_TRANSFORM.reason)
  return _internal_reason();
}
inline void S_FORCED_TRANSFORM::_internal_set_reason(::Protocol::ForcedTransformReason value) {
  
  reason_ = value;
}
inline void S_FORCED_TRANSFORM::set_reason(::Protocol::ForcedTransformReason value) {
  _internal_set_reason(value);
  // @@protoc_insertion_point(field_set:Protocol.S_FORCED_TRANSFORM.reason)
}

// -------------------------------------------------------------------

// C_DEBUG_COMMAND

// .Protocol.DebugCommandType commandType = 1;
inline void C_DEBUG_COMMAND::clear_commandtype() {
  commandtype_ = 0;
}
inline ::Protocol::DebugCommandType C_DEBUG_COMMAND::_internal_commandtype() const {
  return static_cast< ::Protocol::DebugCommandType >(commandtype_);
}
inline ::Protocol::DebugCommandType C_DEBUG_COMMAND::commandtype() const {
  // @@protoc_insertion_point(field_get:Protocol.C_DEBUG_COMMAND.commandType)
  return _internal_commandtype();
}
inline void C_DEBUG_COMMAND::_internal_set_commandtype(::Protocol::DebugCommandType value) {
  
  commandtype_ = value;
}
inline void C_DEBUG_COMMAND::set_commandtype(::Protocol::DebugCommandType value) {
  _internal_set_commandtype(value);
  // @@protoc_insertion_point(field_set:Protocol.C_DEBUG_COMMAND.commandType)
}

// int32 megaGridNumber = 2;
inline void C_DEBUG_COMMAND::clear_megagridnumber() {
  megagridnumber_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 C_DEBUG_COMMAND::_internal_megagridnumber() const {
  return megagridnumber_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 C_DEBUG_COMMAND::megagridnumber() const {
  // @@protoc_insertion_point(field_get:Protocol.C_DEBUG_COMMAND.megaGridNumber)
  return _internal_megagridnumber();
}
inline void C_DEBUG_COMMAND::_internal_set_megagridnumber(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  megagridnumber_ = value;
}
inline void C_DEBUG_COMMAND::set_megagridnumber(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_megagridnumber(value);
  // @@protoc_insertion_point(field_set:Protocol.C_DEBUG_COMMAND.megaGridNumber)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Protocol_2eproto
