// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Struct.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Enum.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Struct_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Struct_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[8]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Struct_2eproto;
namespace Protocol {
class Animation;
struct AnimationDefaultTypeInternal;
extern AnimationDefaultTypeInternal _Animation_default_instance_;
class Building;
struct BuildingDefaultTypeInternal;
extern BuildingDefaultTypeInternal _Building_default_instance_;
class Bullet;
struct BulletDefaultTypeInternal;
extern BulletDefaultTypeInternal _Bullet_default_instance_;
class Enemy;
struct EnemyDefaultTypeInternal;
extern EnemyDefaultTypeInternal _Enemy_default_instance_;
class ObjectStatus;
struct ObjectStatusDefaultTypeInternal;
extern ObjectStatusDefaultTypeInternal _ObjectStatus_default_instance_;
class Player;
struct PlayerDefaultTypeInternal;
extern PlayerDefaultTypeInternal _Player_default_instance_;
class Transform;
struct TransformDefaultTypeInternal;
extern TransformDefaultTypeInternal _Transform_default_instance_;
class Vec3f;
struct Vec3fDefaultTypeInternal;
extern Vec3fDefaultTypeInternal _Vec3f_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::Animation* Arena::CreateMaybeMessage<::Protocol::Animation>(Arena*);
template<> ::Protocol::Building* Arena::CreateMaybeMessage<::Protocol::Building>(Arena*);
template<> ::Protocol::Bullet* Arena::CreateMaybeMessage<::Protocol::Bullet>(Arena*);
template<> ::Protocol::Enemy* Arena::CreateMaybeMessage<::Protocol::Enemy>(Arena*);
template<> ::Protocol::ObjectStatus* Arena::CreateMaybeMessage<::Protocol::ObjectStatus>(Arena*);
template<> ::Protocol::Player* Arena::CreateMaybeMessage<::Protocol::Player>(Arena*);
template<> ::Protocol::Transform* Arena::CreateMaybeMessage<::Protocol::Transform>(Arena*);
template<> ::Protocol::Vec3f* Arena::CreateMaybeMessage<::Protocol::Vec3f>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class Vec3f final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.Vec3f) */ {
 public:
  inline Vec3f() : Vec3f(nullptr) {}
  ~Vec3f() override;
  explicit constexpr Vec3f(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Vec3f(const Vec3f& from);
  Vec3f(Vec3f&& from) noexcept
    : Vec3f() {
    *this = ::std::move(from);
  }

  inline Vec3f& operator=(const Vec3f& from) {
    CopyFrom(from);
    return *this;
  }
  inline Vec3f& operator=(Vec3f&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Vec3f& default_instance() {
    return *internal_default_instance();
  }
  static inline const Vec3f* internal_default_instance() {
    return reinterpret_cast<const Vec3f*>(
               &_Vec3f_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Vec3f& a, Vec3f& b) {
    a.Swap(&b);
  }
  inline void Swap(Vec3f* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Vec3f* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Vec3f* New() const final {
    return new Vec3f();
  }

  Vec3f* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Vec3f>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Vec3f& from);
  void MergeFrom(const Vec3f& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Vec3f* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.Vec3f";
  }
  protected:
  explicit Vec3f(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 3;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.Vec3f)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float x_;
  float y_;
  float z_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class Transform final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.Transform) */ {
 public:
  inline Transform() : Transform(nullptr) {}
  ~Transform() override;
  explicit constexpr Transform(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Transform(const Transform& from);
  Transform(Transform&& from) noexcept
    : Transform() {
    *this = ::std::move(from);
  }

  inline Transform& operator=(const Transform& from) {
    CopyFrom(from);
    return *this;
  }
  inline Transform& operator=(Transform&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Transform& default_instance() {
    return *internal_default_instance();
  }
  static inline const Transform* internal_default_instance() {
    return reinterpret_cast<const Transform*>(
               &_Transform_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Transform& a, Transform& b) {
    a.Swap(&b);
  }
  inline void Swap(Transform* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Transform* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Transform* New() const final {
    return new Transform();
  }

  Transform* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Transform>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Transform& from);
  void MergeFrom(const Transform& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Transform* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.Transform";
  }
  protected:
  explicit Transform(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPositionFieldNumber = 1,
    kScaleFieldNumber = 3,
    kYawFieldNumber = 2,
  };
  // .Protocol.Vec3f position = 1;
  bool has_position() const;
  private:
  bool _internal_has_position() const;
  public:
  void clear_position();
  const ::Protocol::Vec3f& position() const;
  PROTOBUF_FUTURE_MUST_USE_RESULT ::Protocol::Vec3f* release_position();
  ::Protocol::Vec3f* mutable_position();
  void set_allocated_position(::Protocol::Vec3f* position);
  private:
  const ::Protocol::Vec3f& _internal_position() const;
  ::Protocol::Vec3f* _internal_mutable_position();
  public:
  void unsafe_arena_set_allocated_position(
      ::Protocol::Vec3f* position);
  ::Protocol::Vec3f* unsafe_arena_release_position();

  // .Protocol.Vec3f scale = 3;
  bool has_scale() const;
  private:
  bool _internal_has_scale() const;
  public:
  void clear_scale();
  const ::Protocol::Vec3f& scale() const;
  PROTOBUF_FUTURE_MUST_USE_RESULT ::Protocol::Vec3f* release_scale();
  ::Protocol::Vec3f* mutable_scale();
  void set_allocated_scale(::Protocol::Vec3f* scale);
  private:
  const ::Protocol::Vec3f& _internal_scale() const;
  ::Protocol::Vec3f* _internal_mutable_scale();
  public:
  void unsafe_arena_set_allocated_scale(
      ::Protocol::Vec3f* scale);
  ::Protocol::Vec3f* unsafe_arena_release_scale();

  // float yaw = 2;
  void clear_yaw();
  float yaw() const;
  void set_yaw(float value);
  private:
  float _internal_yaw() const;
  void _internal_set_yaw(float value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.Transform)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::Protocol::Vec3f* position_;
  ::Protocol::Vec3f* scale_;
  float yaw_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class ObjectStatus final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.ObjectStatus) */ {
 public:
  inline ObjectStatus() : ObjectStatus(nullptr) {}
  ~ObjectStatus() override;
  explicit constexpr ObjectStatus(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ObjectStatus(const ObjectStatus& from);
  ObjectStatus(ObjectStatus&& from) noexcept
    : ObjectStatus() {
    *this = ::std::move(from);
  }

  inline ObjectStatus& operator=(const ObjectStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline ObjectStatus& operator=(ObjectStatus&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ObjectStatus& default_instance() {
    return *internal_default_instance();
  }
  static inline const ObjectStatus* internal_default_instance() {
    return reinterpret_cast<const ObjectStatus*>(
               &_ObjectStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ObjectStatus& a, ObjectStatus& b) {
    a.Swap(&b);
  }
  inline void Swap(ObjectStatus* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ObjectStatus* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ObjectStatus* New() const final {
    return new ObjectStatus();
  }

  ObjectStatus* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ObjectStatus>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ObjectStatus& from);
  void MergeFrom(const ObjectStatus& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ObjectStatus* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.ObjectStatus";
  }
  protected:
  explicit ObjectStatus(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHpFieldNumber = 1,
    kAttackFieldNumber = 2,
    kDefenseFieldNumber = 3,
    kSpeedFieldNumber = 4,
  };
  // uint32 hp = 1;
  void clear_hp();
  ::PROTOBUF_NAMESPACE_ID::uint32 hp() const;
  void set_hp(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_hp() const;
  void _internal_set_hp(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 attack = 2;
  void clear_attack();
  ::PROTOBUF_NAMESPACE_ID::uint32 attack() const;
  void set_attack(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_attack() const;
  void _internal_set_attack(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 defense = 3;
  void clear_defense();
  ::PROTOBUF_NAMESPACE_ID::uint32 defense() const;
  void set_defense(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_defense() const;
  void _internal_set_defense(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 speed = 4;
  void clear_speed();
  ::PROTOBUF_NAMESPACE_ID::uint32 speed() const;
  void set_speed(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_speed() const;
  void _internal_set_speed(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.ObjectStatus)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint32 hp_;
  ::PROTOBUF_NAMESPACE_ID::uint32 attack_;
  ::PROTOBUF_NAMESPACE_ID::uint32 defense_;
  ::PROTOBUF_NAMESPACE_ID::uint32 speed_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class Animation final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.Animation) */ {
 public:
  inline Animation() : Animation(nullptr) {}
  ~Animation() override;
  explicit constexpr Animation(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Animation(const Animation& from);
  Animation(Animation&& from) noexcept
    : Animation() {
    *this = ::std::move(from);
  }

  inline Animation& operator=(const Animation& from) {
    CopyFrom(from);
    return *this;
  }
  inline Animation& operator=(Animation&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Animation& default_instance() {
    return *internal_default_instance();
  }
  static inline const Animation* internal_default_instance() {
    return reinterpret_cast<const Animation*>(
               &_Animation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Animation& a, Animation& b) {
    a.Swap(&b);
  }
  inline void Swap(Animation* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Animation* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Animation* New() const final {
    return new Animation();
  }

  Animation* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Animation>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Animation& from);
  void MergeFrom(const Animation& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Animation* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.Animation";
  }
  protected:
  explicit Animation(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStateCodeFieldNumber = 1,
    kAnimationTickFieldNumber = 2,
  };
  // uint32 stateCode = 1;
  void clear_statecode();
  ::PROTOBUF_NAMESPACE_ID::uint32 statecode() const;
  void set_statecode(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_statecode() const;
  void _internal_set_statecode(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 animationTick = 2;
  void clear_animationtick();
  ::PROTOBUF_NAMESPACE_ID::uint32 animationtick() const;
  void set_animationtick(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_animationtick() const;
  void _internal_set_animationtick(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.Animation)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint32 statecode_;
  ::PROTOBUF_NAMESPACE_ID::uint32 animationtick_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class Bullet final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.Bullet) */ {
 public:
  inline Bullet() : Bullet(nullptr) {}
  ~Bullet() override;
  explicit constexpr Bullet(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Bullet(const Bullet& from);
  Bullet(Bullet&& from) noexcept
    : Bullet() {
    *this = ::std::move(from);
  }

  inline Bullet& operator=(const Bullet& from) {
    CopyFrom(from);
    return *this;
  }
  inline Bullet& operator=(Bullet&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Bullet& default_instance() {
    return *internal_default_instance();
  }
  static inline const Bullet* internal_default_instance() {
    return reinterpret_cast<const Bullet*>(
               &_Bullet_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Bullet& a, Bullet& b) {
    a.Swap(&b);
  }
  inline void Swap(Bullet* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Bullet* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Bullet* New() const final {
    return new Bullet();
  }

  Bullet* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Bullet>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Bullet& from);
  void MergeFrom(const Bullet& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Bullet* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.Bullet";
  }
  protected:
  explicit Bullet(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPositionFieldNumber = 4,
    kVelocityFieldNumber = 5,
    kIdFieldNumber = 1,
    kOwnerIdFieldNumber = 2,
    kBulletTypeFieldNumber = 3,
  };
  // .Protocol.Vec3f position = 4;
  bool has_position() const;
  private:
  bool _internal_has_position() const;
  public:
  void clear_position();
  const ::Protocol::Vec3f& position() const;
  PROTOBUF_FUTURE_MUST_USE_RESULT ::Protocol::Vec3f* release_position();
  ::Protocol::Vec3f* mutable_position();
  void set_allocated_position(::Protocol::Vec3f* position);
  private:
  const ::Protocol::Vec3f& _internal_position() const;
  ::Protocol::Vec3f* _internal_mutable_position();
  public:
  void unsafe_arena_set_allocated_position(
      ::Protocol::Vec3f* position);
  ::Protocol::Vec3f* unsafe_arena_release_position();

  // .Protocol.Vec3f velocity = 5;
  bool has_velocity() const;
  private:
  bool _internal_has_velocity() const;
  public:
  void clear_velocity();
  const ::Protocol::Vec3f& velocity() const;
  PROTOBUF_FUTURE_MUST_USE_RESULT ::Protocol::Vec3f* release_velocity();
  ::Protocol::Vec3f* mutable_velocity();
  void set_allocated_velocity(::Protocol::Vec3f* velocity);
  private:
  const ::Protocol::Vec3f& _internal_velocity() const;
  ::Protocol::Vec3f* _internal_mutable_velocity();
  public:
  void unsafe_arena_set_allocated_velocity(
      ::Protocol::Vec3f* velocity);
  ::Protocol::Vec3f* unsafe_arena_release_velocity();

  // uint64 id = 1;
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 ownerId = 2;
  void clear_ownerid();
  ::PROTOBUF_NAMESPACE_ID::uint64 ownerid() const;
  void set_ownerid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_ownerid() const;
  void _internal_set_ownerid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // .Protocol.BulletType bulletType = 3;
  void clear_bullettype();
  ::Protocol::BulletType bullettype() const;
  void set_bullettype(::Protocol::BulletType value);
  private:
  ::Protocol::BulletType _internal_bullettype() const;
  void _internal_set_bullettype(::Protocol::BulletType value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.Bullet)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::Protocol::Vec3f* position_;
  ::Protocol::Vec3f* velocity_;
  ::PROTOBUF_NAMESPACE_ID::uint64 id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 ownerid_;
  int bullettype_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class Player final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.Player) */ {
 public:
  inline Player() : Player(nullptr) {}
  ~Player() override;
  explicit constexpr Player(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Player(const Player& from);
  Player(Player&& from) noexcept
    : Player() {
    *this = ::std::move(from);
  }

  inline Player& operator=(const Player& from) {
    CopyFrom(from);
    return *this;
  }
  inline Player& operator=(Player&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Player& default_instance() {
    return *internal_default_instance();
  }
  static inline const Player* internal_default_instance() {
    return reinterpret_cast<const Player*>(
               &_Player_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(Player& a, Player& b) {
    a.Swap(&b);
  }
  inline void Swap(Player* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Player* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Player* New() const final {
    return new Player();
  }

  Player* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Player>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Player& from);
  void MergeFrom(const Player& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Player* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.Player";
  }
  protected:
  explicit Player(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 2,
    kTransformFieldNumber = 5,
    kAnimationFieldNumber = 6,
    kIdFieldNumber = 1,
    kPlayerTypeFieldNumber = 3,
    kPlayerStateFieldNumber = 4,
    kWeaponTypeFieldNumber = 7,
  };
  // string name = 2;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // .Protocol.Transform transform = 5;
  bool has_transform() const;
  private:
  bool _internal_has_transform() const;
  public:
  void clear_transform();
  const ::Protocol::Transform& transform() const;
  PROTOBUF_FUTURE_MUST_USE_RESULT ::Protocol::Transform* release_transform();
  ::Protocol::Transform* mutable_transform();
  void set_allocated_transform(::Protocol::Transform* transform);
  private:
  const ::Protocol::Transform& _internal_transform() const;
  ::Protocol::Transform* _internal_mutable_transform();
  public:
  void unsafe_arena_set_allocated_transform(
      ::Protocol::Transform* transform);
  ::Protocol::Transform* unsafe_arena_release_transform();

  // .Protocol.Animation animation = 6;
  bool has_animation() const;
  private:
  bool _internal_has_animation() const;
  public:
  void clear_animation();
  const ::Protocol::Animation& animation() const;
  PROTOBUF_FUTURE_MUST_USE_RESULT ::Protocol::Animation* release_animation();
  ::Protocol::Animation* mutable_animation();
  void set_allocated_animation(::Protocol::Animation* animation);
  private:
  const ::Protocol::Animation& _internal_animation() const;
  ::Protocol::Animation* _internal_mutable_animation();
  public:
  void unsafe_arena_set_allocated_animation(
      ::Protocol::Animation* animation);
  ::Protocol::Animation* unsafe_arena_release_animation();

  // uint64 id = 1;
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // .Protocol.PlayerType playerType = 3;
  void clear_playertype();
  ::Protocol::PlayerType playertype() const;
  void set_playertype(::Protocol::PlayerType value);
  private:
  ::Protocol::PlayerType _internal_playertype() const;
  void _internal_set_playertype(::Protocol::PlayerType value);
  public:

  // .Protocol.PlayerState playerState = 4;
  void clear_playerstate();
  ::Protocol::PlayerState playerstate() const;
  void set_playerstate(::Protocol::PlayerState value);
  private:
  ::Protocol::PlayerState _internal_playerstate() const;
  void _internal_set_playerstate(::Protocol::PlayerState value);
  public:

  // .Protocol.WeaponType weaponType = 7;
  void clear_weapontype();
  ::Protocol::WeaponType weapontype() const;
  void set_weapontype(::Protocol::WeaponType value);
  private:
  ::Protocol::WeaponType _internal_weapontype() const;
  void _internal_set_weapontype(::Protocol::WeaponType value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.Player)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::Protocol::Transform* transform_;
  ::Protocol::Animation* animation_;
  ::PROTOBUF_NAMESPACE_ID::uint64 id_;
  int playertype_;
  int playerstate_;
  int weapontype_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class Enemy final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.Enemy) */ {
 public:
  inline Enemy() : Enemy(nullptr) {}
  ~Enemy() override;
  explicit constexpr Enemy(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Enemy(const Enemy& from);
  Enemy(Enemy&& from) noexcept
    : Enemy() {
    *this = ::std::move(from);
  }

  inline Enemy& operator=(const Enemy& from) {
    CopyFrom(from);
    return *this;
  }
  inline Enemy& operator=(Enemy&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Enemy& default_instance() {
    return *internal_default_instance();
  }
  static inline const Enemy* internal_default_instance() {
    return reinterpret_cast<const Enemy*>(
               &_Enemy_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(Enemy& a, Enemy& b) {
    a.Swap(&b);
  }
  inline void Swap(Enemy* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Enemy* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Enemy* New() const final {
    return new Enemy();
  }

  Enemy* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Enemy>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Enemy& from);
  void MergeFrom(const Enemy& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Enemy* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.Enemy";
  }
  protected:
  explicit Enemy(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTransformFieldNumber = 4,
    kAnimationFieldNumber = 5,
    kIdFieldNumber = 1,
    kEnemyTypeFieldNumber = 2,
    kEnemyStateFieldNumber = 3,
    kWeaponTypeFieldNumber = 6,
  };
  // .Protocol.Transform transform = 4;
  bool has_transform() const;
  private:
  bool _internal_has_transform() const;
  public:
  void clear_transform();
  const ::Protocol::Transform& transform() const;
  PROTOBUF_FUTURE_MUST_USE_RESULT ::Protocol::Transform* release_transform();
  ::Protocol::Transform* mutable_transform();
  void set_allocated_transform(::Protocol::Transform* transform);
  private:
  const ::Protocol::Transform& _internal_transform() const;
  ::Protocol::Transform* _internal_mutable_transform();
  public:
  void unsafe_arena_set_allocated_transform(
      ::Protocol::Transform* transform);
  ::Protocol::Transform* unsafe_arena_release_transform();

  // .Protocol.Animation animation = 5;
  bool has_animation() const;
  private:
  bool _internal_has_animation() const;
  public:
  void clear_animation();
  const ::Protocol::Animation& animation() const;
  PROTOBUF_FUTURE_MUST_USE_RESULT ::Protocol::Animation* release_animation();
  ::Protocol::Animation* mutable_animation();
  void set_allocated_animation(::Protocol::Animation* animation);
  private:
  const ::Protocol::Animation& _internal_animation() const;
  ::Protocol::Animation* _internal_mutable_animation();
  public:
  void unsafe_arena_set_allocated_animation(
      ::Protocol::Animation* animation);
  ::Protocol::Animation* unsafe_arena_release_animation();

  // uint64 id = 1;
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // .Protocol.EnemyType enemyType = 2;
  void clear_enemytype();
  ::Protocol::EnemyType enemytype() const;
  void set_enemytype(::Protocol::EnemyType value);
  private:
  ::Protocol::EnemyType _internal_enemytype() const;
  void _internal_set_enemytype(::Protocol::EnemyType value);
  public:

  // .Protocol.EnemyState enemyState = 3;
  void clear_enemystate();
  ::Protocol::EnemyState enemystate() const;
  void set_enemystate(::Protocol::EnemyState value);
  private:
  ::Protocol::EnemyState _internal_enemystate() const;
  void _internal_set_enemystate(::Protocol::EnemyState value);
  public:

  // .Protocol.WeaponType weaponType = 6;
  void clear_weapontype();
  ::Protocol::WeaponType weapontype() const;
  void set_weapontype(::Protocol::WeaponType value);
  private:
  ::Protocol::WeaponType _internal_weapontype() const;
  void _internal_set_weapontype(::Protocol::WeaponType value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.Enemy)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::Protocol::Transform* transform_;
  ::Protocol::Animation* animation_;
  ::PROTOBUF_NAMESPACE_ID::uint64 id_;
  int enemytype_;
  int enemystate_;
  int weapontype_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class Building final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.Building) */ {
 public:
  inline Building() : Building(nullptr) {}
  ~Building() override;
  explicit constexpr Building(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Building(const Building& from);
  Building(Building&& from) noexcept
    : Building() {
    *this = ::std::move(from);
  }

  inline Building& operator=(const Building& from) {
    CopyFrom(from);
    return *this;
  }
  inline Building& operator=(Building&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Building& default_instance() {
    return *internal_default_instance();
  }
  static inline const Building* internal_default_instance() {
    return reinterpret_cast<const Building*>(
               &_Building_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(Building& a, Building& b) {
    a.Swap(&b);
  }
  inline void Swap(Building* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Building* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Building* New() const final {
    return new Building();
  }

  Building* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Building>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Building& from);
  void MergeFrom(const Building& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Building* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.Building";
  }
  protected:
  explicit Building(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTransformFieldNumber = 2,
    kIdFieldNumber = 1,
    kBuildingTypeFieldNumber = 3,
  };
  // .Protocol.Transform transform = 2;
  bool has_transform() const;
  private:
  bool _internal_has_transform() const;
  public:
  void clear_transform();
  const ::Protocol::Transform& transform() const;
  PROTOBUF_FUTURE_MUST_USE_RESULT ::Protocol::Transform* release_transform();
  ::Protocol::Transform* mutable_transform();
  void set_allocated_transform(::Protocol::Transform* transform);
  private:
  const ::Protocol::Transform& _internal_transform() const;
  ::Protocol::Transform* _internal_mutable_transform();
  public:
  void unsafe_arena_set_allocated_transform(
      ::Protocol::Transform* transform);
  ::Protocol::Transform* unsafe_arena_release_transform();

  // uint64 id = 1;
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // .Protocol.BuildingType buildingType = 3;
  void clear_buildingtype();
  ::Protocol::BuildingType buildingtype() const;
  void set_buildingtype(::Protocol::BuildingType value);
  private:
  ::Protocol::BuildingType _internal_buildingtype() const;
  void _internal_set_buildingtype(::Protocol::BuildingType value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.Building)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::Protocol::Transform* transform_;
  ::PROTOBUF_NAMESPACE_ID::uint64 id_;
  int buildingtype_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Struct_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Vec3f

// float x = 1;
inline void Vec3f::clear_x() {
  x_ = 0;
}
inline float Vec3f::_internal_x() const {
  return x_;
}
inline float Vec3f::x() const {
  // @@protoc_insertion_point(field_get:Protocol.Vec3f.x)
  return _internal_x();
}
inline void Vec3f::_internal_set_x(float value) {
  
  x_ = value;
}
inline void Vec3f::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:Protocol.Vec3f.x)
}

// float y = 2;
inline void Vec3f::clear_y() {
  y_ = 0;
}
inline float Vec3f::_internal_y() const {
  return y_;
}
inline float Vec3f::y() const {
  // @@protoc_insertion_point(field_get:Protocol.Vec3f.y)
  return _internal_y();
}
inline void Vec3f::_internal_set_y(float value) {
  
  y_ = value;
}
inline void Vec3f::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:Protocol.Vec3f.y)
}

// float z = 3;
inline void Vec3f::clear_z() {
  z_ = 0;
}
inline float Vec3f::_internal_z() const {
  return z_;
}
inline float Vec3f::z() const {
  // @@protoc_insertion_point(field_get:Protocol.Vec3f.z)
  return _internal_z();
}
inline void Vec3f::_internal_set_z(float value) {
  
  z_ = value;
}
inline void Vec3f::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:Protocol.Vec3f.z)
}

// -------------------------------------------------------------------

// Transform

// .Protocol.Vec3f position = 1;
inline bool Transform::_internal_has_position() const {
  return this != internal_default_instance() && position_ != nullptr;
}
inline bool Transform::has_position() const {
  return _internal_has_position();
}
inline void Transform::clear_position() {
  if (GetArenaForAllocation() == nullptr && position_ != nullptr) {
    delete position_;
  }
  position_ = nullptr;
}
inline const ::Protocol::Vec3f& Transform::_internal_position() const {
  const ::Protocol::Vec3f* p = position_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Vec3f&>(
      ::Protocol::_Vec3f_default_instance_);
}
inline const ::Protocol::Vec3f& Transform::position() const {
  // @@protoc_insertion_point(field_get:Protocol.Transform.position)
  return _internal_position();
}
inline void Transform::unsafe_arena_set_allocated_position(
    ::Protocol::Vec3f* position) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(position_);
  }
  position_ = position;
  if (position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.Transform.position)
}
inline ::Protocol::Vec3f* Transform::release_position() {
  
  ::Protocol::Vec3f* temp = position_;
  position_ = nullptr;
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::Protocol::Vec3f* Transform::unsafe_arena_release_position() {
  // @@protoc_insertion_point(field_release:Protocol.Transform.position)
  
  ::Protocol::Vec3f* temp = position_;
  position_ = nullptr;
  return temp;
}
inline ::Protocol::Vec3f* Transform::_internal_mutable_position() {
  
  if (position_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::Vec3f>(GetArenaForAllocation());
    position_ = p;
  }
  return position_;
}
inline ::Protocol::Vec3f* Transform::mutable_position() {
  // @@protoc_insertion_point(field_mutable:Protocol.Transform.position)
  return _internal_mutable_position();
}
inline void Transform::set_allocated_position(::Protocol::Vec3f* position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete position_;
  }
  if (position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::Protocol::Vec3f>::GetOwningArena(position);
    if (message_arena != submessage_arena) {
      position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, position, submessage_arena);
    }
    
  } else {
    
  }
  position_ = position;
  // @@protoc_insertion_point(field_set_allocated:Protocol.Transform.position)
}

// float yaw = 2;
inline void Transform::clear_yaw() {
  yaw_ = 0;
}
inline float Transform::_internal_yaw() const {
  return yaw_;
}
inline float Transform::yaw() const {
  // @@protoc_insertion_point(field_get:Protocol.Transform.yaw)
  return _internal_yaw();
}
inline void Transform::_internal_set_yaw(float value) {
  
  yaw_ = value;
}
inline void Transform::set_yaw(float value) {
  _internal_set_yaw(value);
  // @@protoc_insertion_point(field_set:Protocol.Transform.yaw)
}

// .Protocol.Vec3f scale = 3;
inline bool Transform::_internal_has_scale() const {
  return this != internal_default_instance() && scale_ != nullptr;
}
inline bool Transform::has_scale() const {
  return _internal_has_scale();
}
inline void Transform::clear_scale() {
  if (GetArenaForAllocation() == nullptr && scale_ != nullptr) {
    delete scale_;
  }
  scale_ = nullptr;
}
inline const ::Protocol::Vec3f& Transform::_internal_scale() const {
  const ::Protocol::Vec3f* p = scale_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Vec3f&>(
      ::Protocol::_Vec3f_default_instance_);
}
inline const ::Protocol::Vec3f& Transform::scale() const {
  // @@protoc_insertion_point(field_get:Protocol.Transform.scale)
  return _internal_scale();
}
inline void Transform::unsafe_arena_set_allocated_scale(
    ::Protocol::Vec3f* scale) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(scale_);
  }
  scale_ = scale;
  if (scale) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.Transform.scale)
}
inline ::Protocol::Vec3f* Transform::release_scale() {
  
  ::Protocol::Vec3f* temp = scale_;
  scale_ = nullptr;
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::Protocol::Vec3f* Transform::unsafe_arena_release_scale() {
  // @@protoc_insertion_point(field_release:Protocol.Transform.scale)
  
  ::Protocol::Vec3f* temp = scale_;
  scale_ = nullptr;
  return temp;
}
inline ::Protocol::Vec3f* Transform::_internal_mutable_scale() {
  
  if (scale_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::Vec3f>(GetArenaForAllocation());
    scale_ = p;
  }
  return scale_;
}
inline ::Protocol::Vec3f* Transform::mutable_scale() {
  // @@protoc_insertion_point(field_mutable:Protocol.Transform.scale)
  return _internal_mutable_scale();
}
inline void Transform::set_allocated_scale(::Protocol::Vec3f* scale) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete scale_;
  }
  if (scale) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::Protocol::Vec3f>::GetOwningArena(scale);
    if (message_arena != submessage_arena) {
      scale = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, scale, submessage_arena);
    }
    
  } else {
    
  }
  scale_ = scale;
  // @@protoc_insertion_point(field_set_allocated:Protocol.Transform.scale)
}

// -------------------------------------------------------------------

// ObjectStatus

// uint32 hp = 1;
inline void ObjectStatus::clear_hp() {
  hp_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ObjectStatus::_internal_hp() const {
  return hp_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ObjectStatus::hp() const {
  // @@protoc_insertion_point(field_get:Protocol.ObjectStatus.hp)
  return _internal_hp();
}
inline void ObjectStatus::_internal_set_hp(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  hp_ = value;
}
inline void ObjectStatus::set_hp(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_hp(value);
  // @@protoc_insertion_point(field_set:Protocol.ObjectStatus.hp)
}

// uint32 attack = 2;
inline void ObjectStatus::clear_attack() {
  attack_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ObjectStatus::_internal_attack() const {
  return attack_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ObjectStatus::attack() const {
  // @@protoc_insertion_point(field_get:Protocol.ObjectStatus.attack)
  return _internal_attack();
}
inline void ObjectStatus::_internal_set_attack(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  attack_ = value;
}
inline void ObjectStatus::set_attack(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_attack(value);
  // @@protoc_insertion_point(field_set:Protocol.ObjectStatus.attack)
}

// uint32 defense = 3;
inline void ObjectStatus::clear_defense() {
  defense_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ObjectStatus::_internal_defense() const {
  return defense_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ObjectStatus::defense() const {
  // @@protoc_insertion_point(field_get:Protocol.ObjectStatus.defense)
  return _internal_defense();
}
inline void ObjectStatus::_internal_set_defense(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  defense_ = value;
}
inline void ObjectStatus::set_defense(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_defense(value);
  // @@protoc_insertion_point(field_set:Protocol.ObjectStatus.defense)
}

// uint32 speed = 4;
inline void ObjectStatus::clear_speed() {
  speed_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ObjectStatus::_internal_speed() const {
  return speed_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ObjectStatus::speed() const {
  // @@protoc_insertion_point(field_get:Protocol.ObjectStatus.speed)
  return _internal_speed();
}
inline void ObjectStatus::_internal_set_speed(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  speed_ = value;
}
inline void ObjectStatus::set_speed(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_speed(value);
  // @@protoc_insertion_point(field_set:Protocol.ObjectStatus.speed)
}

// -------------------------------------------------------------------

// Animation

// uint32 stateCode = 1;
inline void Animation::clear_statecode() {
  statecode_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Animation::_internal_statecode() const {
  return statecode_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Animation::statecode() const {
  // @@protoc_insertion_point(field_get:Protocol.Animation.stateCode)
  return _internal_statecode();
}
inline void Animation::_internal_set_statecode(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  statecode_ = value;
}
inline void Animation::set_statecode(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_statecode(value);
  // @@protoc_insertion_point(field_set:Protocol.Animation.stateCode)
}

// uint32 animationTick = 2;
inline void Animation::clear_animationtick() {
  animationtick_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Animation::_internal_animationtick() const {
  return animationtick_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Animation::animationtick() const {
  // @@protoc_insertion_point(field_get:Protocol.Animation.animationTick)
  return _internal_animationtick();
}
inline void Animation::_internal_set_animationtick(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  animationtick_ = value;
}
inline void Animation::set_animationtick(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_animationtick(value);
  // @@protoc_insertion_point(field_set:Protocol.Animation.animationTick)
}

// -------------------------------------------------------------------

// Bullet

// uint64 id = 1;
inline void Bullet::clear_id() {
  id_ = uint64_t{0u};
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Bullet::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Bullet::id() const {
  // @@protoc_insertion_point(field_get:Protocol.Bullet.id)
  return _internal_id();
}
inline void Bullet::_internal_set_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  id_ = value;
}
inline void Bullet::set_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:Protocol.Bullet.id)
}

// uint64 ownerId = 2;
inline void Bullet::clear_ownerid() {
  ownerid_ = uint64_t{0u};
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Bullet::_internal_ownerid() const {
  return ownerid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Bullet::ownerid() const {
  // @@protoc_insertion_point(field_get:Protocol.Bullet.ownerId)
  return _internal_ownerid();
}
inline void Bullet::_internal_set_ownerid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  ownerid_ = value;
}
inline void Bullet::set_ownerid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_ownerid(value);
  // @@protoc_insertion_point(field_set:Protocol.Bullet.ownerId)
}

// .Protocol.BulletType bulletType = 3;
inline void Bullet::clear_bullettype() {
  bullettype_ = 0;
}
inline ::Protocol::BulletType Bullet::_internal_bullettype() const {
  return static_cast< ::Protocol::BulletType >(bullettype_);
}
inline ::Protocol::BulletType Bullet::bullettype() const {
  // @@protoc_insertion_point(field_get:Protocol.Bullet.bulletType)
  return _internal_bullettype();
}
inline void Bullet::_internal_set_bullettype(::Protocol::BulletType value) {
  
  bullettype_ = value;
}
inline void Bullet::set_bullettype(::Protocol::BulletType value) {
  _internal_set_bullettype(value);
  // @@protoc_insertion_point(field_set:Protocol.Bullet.bulletType)
}

// .Protocol.Vec3f position = 4;
inline bool Bullet::_internal_has_position() const {
  return this != internal_default_instance() && position_ != nullptr;
}
inline bool Bullet::has_position() const {
  return _internal_has_position();
}
inline void Bullet::clear_position() {
  if (GetArenaForAllocation() == nullptr && position_ != nullptr) {
    delete position_;
  }
  position_ = nullptr;
}
inline const ::Protocol::Vec3f& Bullet::_internal_position() const {
  const ::Protocol::Vec3f* p = position_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Vec3f&>(
      ::Protocol::_Vec3f_default_instance_);
}
inline const ::Protocol::Vec3f& Bullet::position() const {
  // @@protoc_insertion_point(field_get:Protocol.Bullet.position)
  return _internal_position();
}
inline void Bullet::unsafe_arena_set_allocated_position(
    ::Protocol::Vec3f* position) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(position_);
  }
  position_ = position;
  if (position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.Bullet.position)
}
inline ::Protocol::Vec3f* Bullet::release_position() {
  
  ::Protocol::Vec3f* temp = position_;
  position_ = nullptr;
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::Protocol::Vec3f* Bullet::unsafe_arena_release_position() {
  // @@protoc_insertion_point(field_release:Protocol.Bullet.position)
  
  ::Protocol::Vec3f* temp = position_;
  position_ = nullptr;
  return temp;
}
inline ::Protocol::Vec3f* Bullet::_internal_mutable_position() {
  
  if (position_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::Vec3f>(GetArenaForAllocation());
    position_ = p;
  }
  return position_;
}
inline ::Protocol::Vec3f* Bullet::mutable_position() {
  // @@protoc_insertion_point(field_mutable:Protocol.Bullet.position)
  return _internal_mutable_position();
}
inline void Bullet::set_allocated_position(::Protocol::Vec3f* position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete position_;
  }
  if (position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::Protocol::Vec3f>::GetOwningArena(position);
    if (message_arena != submessage_arena) {
      position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, position, submessage_arena);
    }
    
  } else {
    
  }
  position_ = position;
  // @@protoc_insertion_point(field_set_allocated:Protocol.Bullet.position)
}

// .Protocol.Vec3f velocity = 5;
inline bool Bullet::_internal_has_velocity() const {
  return this != internal_default_instance() && velocity_ != nullptr;
}
inline bool Bullet::has_velocity() const {
  return _internal_has_velocity();
}
inline void Bullet::clear_velocity() {
  if (GetArenaForAllocation() == nullptr && velocity_ != nullptr) {
    delete velocity_;
  }
  velocity_ = nullptr;
}
inline const ::Protocol::Vec3f& Bullet::_internal_velocity() const {
  const ::Protocol::Vec3f* p = velocity_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Vec3f&>(
      ::Protocol::_Vec3f_default_instance_);
}
inline const ::Protocol::Vec3f& Bullet::velocity() const {
  // @@protoc_insertion_point(field_get:Protocol.Bullet.velocity)
  return _internal_velocity();
}
inline void Bullet::unsafe_arena_set_allocated_velocity(
    ::Protocol::Vec3f* velocity) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(velocity_);
  }
  velocity_ = velocity;
  if (velocity) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.Bullet.velocity)
}
inline ::Protocol::Vec3f* Bullet::release_velocity() {
  
  ::Protocol::Vec3f* temp = velocity_;
  velocity_ = nullptr;
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::Protocol::Vec3f* Bullet::unsafe_arena_release_velocity() {
  // @@protoc_insertion_point(field_release:Protocol.Bullet.velocity)
  
  ::Protocol::Vec3f* temp = velocity_;
  velocity_ = nullptr;
  return temp;
}
inline ::Protocol::Vec3f* Bullet::_internal_mutable_velocity() {
  
  if (velocity_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::Vec3f>(GetArenaForAllocation());
    velocity_ = p;
  }
  return velocity_;
}
inline ::Protocol::Vec3f* Bullet::mutable_velocity() {
  // @@protoc_insertion_point(field_mutable:Protocol.Bullet.velocity)
  return _internal_mutable_velocity();
}
inline void Bullet::set_allocated_velocity(::Protocol::Vec3f* velocity) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete velocity_;
  }
  if (velocity) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::Protocol::Vec3f>::GetOwningArena(velocity);
    if (message_arena != submessage_arena) {
      velocity = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, velocity, submessage_arena);
    }
    
  } else {
    
  }
  velocity_ = velocity;
  // @@protoc_insertion_point(field_set_allocated:Protocol.Bullet.velocity)
}

// -------------------------------------------------------------------

// Player

// uint64 id = 1;
inline void Player::clear_id() {
  id_ = uint64_t{0u};
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Player::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Player::id() const {
  // @@protoc_insertion_point(field_get:Protocol.Player.id)
  return _internal_id();
}
inline void Player::_internal_set_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  id_ = value;
}
inline void Player::set_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:Protocol.Player.id)
}

// string name = 2;
inline void Player::clear_name() {
  name_.ClearToEmpty();
}
inline const std::string& Player::name() const {
  // @@protoc_insertion_point(field_get:Protocol.Player.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Player::set_name(ArgT0&& arg0, ArgT... args) {
 
 name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.Player.name)
}
inline std::string* Player::mutable_name() {
  // @@protoc_insertion_point(field_mutable:Protocol.Player.name)
  return _internal_mutable_name();
}
inline const std::string& Player::_internal_name() const {
  return name_.Get();
}
inline void Player::_internal_set_name(const std::string& value) {
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Player::_internal_mutable_name() {
  
  return name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Player::release_name() {
  // @@protoc_insertion_point(field_release:Protocol.Player.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Player::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:Protocol.Player.name)
}

// .Protocol.PlayerType playerType = 3;
inline void Player::clear_playertype() {
  playertype_ = 0;
}
inline ::Protocol::PlayerType Player::_internal_playertype() const {
  return static_cast< ::Protocol::PlayerType >(playertype_);
}
inline ::Protocol::PlayerType Player::playertype() const {
  // @@protoc_insertion_point(field_get:Protocol.Player.playerType)
  return _internal_playertype();
}
inline void Player::_internal_set_playertype(::Protocol::PlayerType value) {
  
  playertype_ = value;
}
inline void Player::set_playertype(::Protocol::PlayerType value) {
  _internal_set_playertype(value);
  // @@protoc_insertion_point(field_set:Protocol.Player.playerType)
}

// .Protocol.PlayerState playerState = 4;
inline void Player::clear_playerstate() {
  playerstate_ = 0;
}
inline ::Protocol::PlayerState Player::_internal_playerstate() const {
  return static_cast< ::Protocol::PlayerState >(playerstate_);
}
inline ::Protocol::PlayerState Player::playerstate() const {
  // @@protoc_insertion_point(field_get:Protocol.Player.playerState)
  return _internal_playerstate();
}
inline void Player::_internal_set_playerstate(::Protocol::PlayerState value) {
  
  playerstate_ = value;
}
inline void Player::set_playerstate(::Protocol::PlayerState value) {
  _internal_set_playerstate(value);
  // @@protoc_insertion_point(field_set:Protocol.Player.playerState)
}

// .Protocol.Transform transform = 5;
inline bool Player::_internal_has_transform() const {
  return this != internal_default_instance() && transform_ != nullptr;
}
inline bool Player::has_transform() const {
  return _internal_has_transform();
}
inline void Player::clear_transform() {
  if (GetArenaForAllocation() == nullptr && transform_ != nullptr) {
    delete transform_;
  }
  transform_ = nullptr;
}
inline const ::Protocol::Transform& Player::_internal_transform() const {
  const ::Protocol::Transform* p = transform_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Transform&>(
      ::Protocol::_Transform_default_instance_);
}
inline const ::Protocol::Transform& Player::transform() const {
  // @@protoc_insertion_point(field_get:Protocol.Player.transform)
  return _internal_transform();
}
inline void Player::unsafe_arena_set_allocated_transform(
    ::Protocol::Transform* transform) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(transform_);
  }
  transform_ = transform;
  if (transform) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.Player.transform)
}
inline ::Protocol::Transform* Player::release_transform() {
  
  ::Protocol::Transform* temp = transform_;
  transform_ = nullptr;
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::Protocol::Transform* Player::unsafe_arena_release_transform() {
  // @@protoc_insertion_point(field_release:Protocol.Player.transform)
  
  ::Protocol::Transform* temp = transform_;
  transform_ = nullptr;
  return temp;
}
inline ::Protocol::Transform* Player::_internal_mutable_transform() {
  
  if (transform_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::Transform>(GetArenaForAllocation());
    transform_ = p;
  }
  return transform_;
}
inline ::Protocol::Transform* Player::mutable_transform() {
  // @@protoc_insertion_point(field_mutable:Protocol.Player.transform)
  return _internal_mutable_transform();
}
inline void Player::set_allocated_transform(::Protocol::Transform* transform) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete transform_;
  }
  if (transform) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::Protocol::Transform>::GetOwningArena(transform);
    if (message_arena != submessage_arena) {
      transform = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, transform, submessage_arena);
    }
    
  } else {
    
  }
  transform_ = transform;
  // @@protoc_insertion_point(field_set_allocated:Protocol.Player.transform)
}

// .Protocol.Animation animation = 6;
inline bool Player::_internal_has_animation() const {
  return this != internal_default_instance() && animation_ != nullptr;
}
inline bool Player::has_animation() const {
  return _internal_has_animation();
}
inline void Player::clear_animation() {
  if (GetArenaForAllocation() == nullptr && animation_ != nullptr) {
    delete animation_;
  }
  animation_ = nullptr;
}
inline const ::Protocol::Animation& Player::_internal_animation() const {
  const ::Protocol::Animation* p = animation_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Animation&>(
      ::Protocol::_Animation_default_instance_);
}
inline const ::Protocol::Animation& Player::animation() const {
  // @@protoc_insertion_point(field_get:Protocol.Player.animation)
  return _internal_animation();
}
inline void Player::unsafe_arena_set_allocated_animation(
    ::Protocol::Animation* animation) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(animation_);
  }
  animation_ = animation;
  if (animation) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.Player.animation)
}
inline ::Protocol::Animation* Player::release_animation() {
  
  ::Protocol::Animation* temp = animation_;
  animation_ = nullptr;
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::Protocol::Animation* Player::unsafe_arena_release_animation() {
  // @@protoc_insertion_point(field_release:Protocol.Player.animation)
  
  ::Protocol::Animation* temp = animation_;
  animation_ = nullptr;
  return temp;
}
inline ::Protocol::Animation* Player::_internal_mutable_animation() {
  
  if (animation_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::Animation>(GetArenaForAllocation());
    animation_ = p;
  }
  return animation_;
}
inline ::Protocol::Animation* Player::mutable_animation() {
  // @@protoc_insertion_point(field_mutable:Protocol.Player.animation)
  return _internal_mutable_animation();
}
inline void Player::set_allocated_animation(::Protocol::Animation* animation) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete animation_;
  }
  if (animation) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::Protocol::Animation>::GetOwningArena(animation);
    if (message_arena != submessage_arena) {
      animation = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, animation, submessage_arena);
    }
    
  } else {
    
  }
  animation_ = animation;
  // @@protoc_insertion_point(field_set_allocated:Protocol.Player.animation)
}

// .Protocol.WeaponType weaponType = 7;
inline void Player::clear_weapontype() {
  weapontype_ = 0;
}
inline ::Protocol::WeaponType Player::_internal_weapontype() const {
  return static_cast< ::Protocol::WeaponType >(weapontype_);
}
inline ::Protocol::WeaponType Player::weapontype() const {
  // @@protoc_insertion_point(field_get:Protocol.Player.weaponType)
  return _internal_weapontype();
}
inline void Player::_internal_set_weapontype(::Protocol::WeaponType value) {
  
  weapontype_ = value;
}
inline void Player::set_weapontype(::Protocol::WeaponType value) {
  _internal_set_weapontype(value);
  // @@protoc_insertion_point(field_set:Protocol.Player.weaponType)
}

// -------------------------------------------------------------------

// Enemy

// uint64 id = 1;
inline void Enemy::clear_id() {
  id_ = uint64_t{0u};
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Enemy::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Enemy::id() const {
  // @@protoc_insertion_point(field_get:Protocol.Enemy.id)
  return _internal_id();
}
inline void Enemy::_internal_set_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  id_ = value;
}
inline void Enemy::set_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:Protocol.Enemy.id)
}

// .Protocol.EnemyType enemyType = 2;
inline void Enemy::clear_enemytype() {
  enemytype_ = 0;
}
inline ::Protocol::EnemyType Enemy::_internal_enemytype() const {
  return static_cast< ::Protocol::EnemyType >(enemytype_);
}
inline ::Protocol::EnemyType Enemy::enemytype() const {
  // @@protoc_insertion_point(field_get:Protocol.Enemy.enemyType)
  return _internal_enemytype();
}
inline void Enemy::_internal_set_enemytype(::Protocol::EnemyType value) {
  
  enemytype_ = value;
}
inline void Enemy::set_enemytype(::Protocol::EnemyType value) {
  _internal_set_enemytype(value);
  // @@protoc_insertion_point(field_set:Protocol.Enemy.enemyType)
}

// .Protocol.EnemyState enemyState = 3;
inline void Enemy::clear_enemystate() {
  enemystate_ = 0;
}
inline ::Protocol::EnemyState Enemy::_internal_enemystate() const {
  return static_cast< ::Protocol::EnemyState >(enemystate_);
}
inline ::Protocol::EnemyState Enemy::enemystate() const {
  // @@protoc_insertion_point(field_get:Protocol.Enemy.enemyState)
  return _internal_enemystate();
}
inline void Enemy::_internal_set_enemystate(::Protocol::EnemyState value) {
  
  enemystate_ = value;
}
inline void Enemy::set_enemystate(::Protocol::EnemyState value) {
  _internal_set_enemystate(value);
  // @@protoc_insertion_point(field_set:Protocol.Enemy.enemyState)
}

// .Protocol.Transform transform = 4;
inline bool Enemy::_internal_has_transform() const {
  return this != internal_default_instance() && transform_ != nullptr;
}
inline bool Enemy::has_transform() const {
  return _internal_has_transform();
}
inline void Enemy::clear_transform() {
  if (GetArenaForAllocation() == nullptr && transform_ != nullptr) {
    delete transform_;
  }
  transform_ = nullptr;
}
inline const ::Protocol::Transform& Enemy::_internal_transform() const {
  const ::Protocol::Transform* p = transform_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Transform&>(
      ::Protocol::_Transform_default_instance_);
}
inline const ::Protocol::Transform& Enemy::transform() const {
  // @@protoc_insertion_point(field_get:Protocol.Enemy.transform)
  return _internal_transform();
}
inline void Enemy::unsafe_arena_set_allocated_transform(
    ::Protocol::Transform* transform) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(transform_);
  }
  transform_ = transform;
  if (transform) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.Enemy.transform)
}
inline ::Protocol::Transform* Enemy::release_transform() {
  
  ::Protocol::Transform* temp = transform_;
  transform_ = nullptr;
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::Protocol::Transform* Enemy::unsafe_arena_release_transform() {
  // @@protoc_insertion_point(field_release:Protocol.Enemy.transform)
  
  ::Protocol::Transform* temp = transform_;
  transform_ = nullptr;
  return temp;
}
inline ::Protocol::Transform* Enemy::_internal_mutable_transform() {
  
  if (transform_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::Transform>(GetArenaForAllocation());
    transform_ = p;
  }
  return transform_;
}
inline ::Protocol::Transform* Enemy::mutable_transform() {
  // @@protoc_insertion_point(field_mutable:Protocol.Enemy.transform)
  return _internal_mutable_transform();
}
inline void Enemy::set_allocated_transform(::Protocol::Transform* transform) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete transform_;
  }
  if (transform) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::Protocol::Transform>::GetOwningArena(transform);
    if (message_arena != submessage_arena) {
      transform = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, transform, submessage_arena);
    }
    
  } else {
    
  }
  transform_ = transform;
  // @@protoc_insertion_point(field_set_allocated:Protocol.Enemy.transform)
}

// .Protocol.Animation animation = 5;
inline bool Enemy::_internal_has_animation() const {
  return this != internal_default_instance() && animation_ != nullptr;
}
inline bool Enemy::has_animation() const {
  return _internal_has_animation();
}
inline void Enemy::clear_animation() {
  if (GetArenaForAllocation() == nullptr && animation_ != nullptr) {
    delete animation_;
  }
  animation_ = nullptr;
}
inline const ::Protocol::Animation& Enemy::_internal_animation() const {
  const ::Protocol::Animation* p = animation_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Animation&>(
      ::Protocol::_Animation_default_instance_);
}
inline const ::Protocol::Animation& Enemy::animation() const {
  // @@protoc_insertion_point(field_get:Protocol.Enemy.animation)
  return _internal_animation();
}
inline void Enemy::unsafe_arena_set_allocated_animation(
    ::Protocol::Animation* animation) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(animation_);
  }
  animation_ = animation;
  if (animation) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.Enemy.animation)
}
inline ::Protocol::Animation* Enemy::release_animation() {
  
  ::Protocol::Animation* temp = animation_;
  animation_ = nullptr;
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::Protocol::Animation* Enemy::unsafe_arena_release_animation() {
  // @@protoc_insertion_point(field_release:Protocol.Enemy.animation)
  
  ::Protocol::Animation* temp = animation_;
  animation_ = nullptr;
  return temp;
}
inline ::Protocol::Animation* Enemy::_internal_mutable_animation() {
  
  if (animation_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::Animation>(GetArenaForAllocation());
    animation_ = p;
  }
  return animation_;
}
inline ::Protocol::Animation* Enemy::mutable_animation() {
  // @@protoc_insertion_point(field_mutable:Protocol.Enemy.animation)
  return _internal_mutable_animation();
}
inline void Enemy::set_allocated_animation(::Protocol::Animation* animation) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete animation_;
  }
  if (animation) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::Protocol::Animation>::GetOwningArena(animation);
    if (message_arena != submessage_arena) {
      animation = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, animation, submessage_arena);
    }
    
  } else {
    
  }
  animation_ = animation;
  // @@protoc_insertion_point(field_set_allocated:Protocol.Enemy.animation)
}

// .Protocol.WeaponType weaponType = 6;
inline void Enemy::clear_weapontype() {
  weapontype_ = 0;
}
inline ::Protocol::WeaponType Enemy::_internal_weapontype() const {
  return static_cast< ::Protocol::WeaponType >(weapontype_);
}
inline ::Protocol::WeaponType Enemy::weapontype() const {
  // @@protoc_insertion_point(field_get:Protocol.Enemy.weaponType)
  return _internal_weapontype();
}
inline void Enemy::_internal_set_weapontype(::Protocol::WeaponType value) {
  
  weapontype_ = value;
}
inline void Enemy::set_weapontype(::Protocol::WeaponType value) {
  _internal_set_weapontype(value);
  // @@protoc_insertion_point(field_set:Protocol.Enemy.weaponType)
}

// -------------------------------------------------------------------

// Building

// uint64 id = 1;
inline void Building::clear_id() {
  id_ = uint64_t{0u};
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Building::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Building::id() const {
  // @@protoc_insertion_point(field_get:Protocol.Building.id)
  return _internal_id();
}
inline void Building::_internal_set_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  id_ = value;
}
inline void Building::set_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:Protocol.Building.id)
}

// .Protocol.Transform transform = 2;
inline bool Building::_internal_has_transform() const {
  return this != internal_default_instance() && transform_ != nullptr;
}
inline bool Building::has_transform() const {
  return _internal_has_transform();
}
inline void Building::clear_transform() {
  if (GetArenaForAllocation() == nullptr && transform_ != nullptr) {
    delete transform_;
  }
  transform_ = nullptr;
}
inline const ::Protocol::Transform& Building::_internal_transform() const {
  const ::Protocol::Transform* p = transform_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Transform&>(
      ::Protocol::_Transform_default_instance_);
}
inline const ::Protocol::Transform& Building::transform() const {
  // @@protoc_insertion_point(field_get:Protocol.Building.transform)
  return _internal_transform();
}
inline void Building::unsafe_arena_set_allocated_transform(
    ::Protocol::Transform* transform) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(transform_);
  }
  transform_ = transform;
  if (transform) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.Building.transform)
}
inline ::Protocol::Transform* Building::release_transform() {
  
  ::Protocol::Transform* temp = transform_;
  transform_ = nullptr;
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::Protocol::Transform* Building::unsafe_arena_release_transform() {
  // @@protoc_insertion_point(field_release:Protocol.Building.transform)
  
  ::Protocol::Transform* temp = transform_;
  transform_ = nullptr;
  return temp;
}
inline ::Protocol::Transform* Building::_internal_mutable_transform() {
  
  if (transform_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::Transform>(GetArenaForAllocation());
    transform_ = p;
  }
  return transform_;
}
inline ::Protocol::Transform* Building::mutable_transform() {
  // @@protoc_insertion_point(field_mutable:Protocol.Building.transform)
  return _internal_mutable_transform();
}
inline void Building::set_allocated_transform(::Protocol::Transform* transform) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete transform_;
  }
  if (transform) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::Protocol::Transform>::GetOwningArena(transform);
    if (message_arena != submessage_arena) {
      transform = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, transform, submessage_arena);
    }
    
  } else {
    
  }
  transform_ = transform;
  // @@protoc_insertion_point(field_set_allocated:Protocol.Building.transform)
}

// .Protocol.BuildingType buildingType = 3;
inline void Building::clear_buildingtype() {
  buildingtype_ = 0;
}
inline ::Protocol::BuildingType Building::_internal_buildingtype() const {
  return static_cast< ::Protocol::BuildingType >(buildingtype_);
}
inline ::Protocol::BuildingType Building::buildingtype() const {
  // @@protoc_insertion_point(field_get:Protocol.Building.buildingType)
  return _internal_buildingtype();
}
inline void Building::_internal_set_buildingtype(::Protocol::BuildingType value) {
  
  buildingtype_ = value;
}
inline void Building::set_buildingtype(::Protocol::BuildingType value) {
  _internal_set_buildingtype(value);
  // @@protoc_insertion_point(field_set:Protocol.Building.buildingType)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto
